export interface Influencer {
  handle: string
  name: string
  followers: string
  avatar: string // emoji fallback
}

export interface Restaurant {
  id: string
  name: string
  cuisine: string
  city: string
  address: string
  priceRange: '€' | '€€' | '€€€' | '€€€€'
  rating: number
  cover: string
  coverEmoji: string
  tags: string[]
  recommendedBy: Influencer
  instagramPost: string
  description: string
  lat: number
  lng: number
}

export const CITIES = ['Toutes les villes', 'Paris', 'Lyon', 'Marseille', 'Bordeaux', 'Nice', 'Toulouse']
export const CUISINES = ['Toutes les cuisines', 'Française', 'Japonaise', 'Italienne', 'Coréenne', 'Mexicaine', 'Libanaise', 'Grecque', 'Péruvienne', 'Végétarienne', 'Américaine', 'Britannique', 'Vietnamienne', 'Thaïlandaise', 'Antillaise', 'Chinoise']

export const RESTAURANTS: Restaurant[] = [
  {
    id: '1',
    name: 'Kibo',
    cuisine: 'Japonaise',
    city: 'Paris',
    address: '18 rue du Faubourg Saint-Antoine, 75011',
    priceRange: '€€€',
    rating: 4.8,
    cover: '#FDF0FD',
    coverEmoji: '🍣',
    tags: ['Omakase', 'Incontournable', 'Réservation obligatoire'],
    recommendedBy: {
      handle: '@philoudarblay',
      name: 'Philou d\'Arblay',
      followers: '310K',
      avatar: '👩‍🍳',
    },
    instagramPost: 'https://www.instagram.com/philoudarblay',
    description: 'Un comptoir omakase confidentiel où le chef propose 12 services autour du meilleur poisson de saison. Liste d\'attente de plusieurs semaines.',
    lat: 48.8535,
    lng: 2.3714,
  },
  {
    id: '13',
    name: 'Club Cochon L\'Auberge',
    cuisine: 'Française',
    city: 'Paris',
    address: '4 rue Drouot, 75009',
    priceRange: '€€',
    rating: 4.6,
    cover: '#FFF8EC',
    coverEmoji: '🐷',
    tags: ['Bistrot', 'Canaille', 'Vin nature'],
    recommendedBy: {
      handle: '@philoudarblay',
      name: 'Philou d\'Arblay',
      followers: '310K',
      avatar: '👩‍🍳',
    },
    instagramPost: 'https://www.instagram.com/philoudarblay',
    description: 'Le bistrot canaille de la rue Drouot, prolongement de l\'emblématique Club Cochon du Passage des Panoramas. Cuisine du cochon de la tête aux pieds, vins nature et ambiance de comptoir chaleureuse.',
    lat: 48.8757,
    lng: 2.3464,
  },
  {
    id: '14',
    name: 'L\'Auberge des Crus',
    cuisine: 'Française',
    city: 'Paris',
    address: '13 rue Bosio, 75016',
    priceRange: '€€€',
    rating: 4.7,
    cover: '#EBE9FA',
    coverEmoji: '🍾',
    tags: ['Terroir', 'Cave', 'Bistrot chic'],
    recommendedBy: {
      handle: '@philoudarblay',
      name: 'Philou d\'Arblay',
      followers: '310K',
      avatar: '👩‍🍳',
    },
    instagramPost: 'https://www.instagram.com/philoudarblay',
    description: 'Atmosphère de maison de campagne en plein Paris 16e. Boiseries, bar en bois des années 40 et cave à vins dédiée à la dégustation. Cuisine du terroir signée par le chef Charles Laborde.',
    lat: 48.8552,
    lng: 2.2706,
  },
  {
    id: '15',
    name: 'Spécimen Burger Saint-Germain',
    cuisine: 'Américaine',
    city: 'Paris',
    address: '3 Rue Guisarde, 75006',
    priceRange: '€€',
    rating: 4.5,
    cover: '#FFF8EC',
    coverEmoji: '🍔',
    tags: ['Burger', 'Saint-Germain', 'Fait maison'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/philoudarblay',
    description: 'Le burger gastronomique de Saint-Germain-des-Prés. Viande sélectionnée, buns maison et sauces signature dans un cadre soigné.',
    lat: 48.8524, lng: 2.3353,
  },
  {
    id: '16',
    name: 'Club Cochon',
    cuisine: 'Française',
    city: 'Paris',
    address: '38 Passage des Panoramas, 75002',
    priceRange: '€€',
    rating: 4.7,
    cover: '#FFF8EC',
    coverEmoji: '🐷',
    tags: ['Bistrot', 'Cochon', 'Passage couvert'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/philoudarblay',
    description: 'L\'adresse historique du Club Cochon, nichée dans le mythique Passage des Panoramas. Fromage de tête, rillettes et cochon de lait rôti dans un décor de comptoir parisien.',
    lat: 48.8697, lng: 2.3453,
  },
  {
    id: '17',
    name: 'Chez Margaux',
    cuisine: 'Française',
    city: 'Paris',
    address: '10 Avenue de New York, 75116',
    priceRange: '€€€',
    rating: 4.6,
    cover: '#ECF8F6',
    coverEmoji: '🌿',
    tags: ['Vue Seine', 'Terrasse', 'Bistronomique'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/philoudarblay',
    description: 'Face à la Seine et au Trocadéro, Chez Margaux propose une cuisine française soignée avec l\'une des plus belles terrasses de Paris. Poissons du marché et viandes rôties.',
    lat: 48.8631, lng: 2.2936,
  },
  {
    id: '18',
    name: 'À La Renaissance',
    cuisine: 'Française',
    city: 'Paris',
    address: '87 Rue de la Roquette, 75011',
    priceRange: '€€',
    rating: 4.5,
    cover: '#EBE9FA',
    coverEmoji: '🍷',
    tags: ['Bistrot de quartier', 'Vin nature', 'Oberkampf'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/philoudarblay',
    description: 'Un bistrot authentique de la Roquette, resté dans son jus depuis des décennies. Cave à vins de caractère et plats du jour généreux à l\'ardoise.',
    lat: 48.8563, lng: 2.3756,
  },
  {
    id: '19',
    name: 'Bistrot Darsy',
    cuisine: 'Française',
    city: 'Paris',
    address: '15 Rue des Panoyaux, 75020',
    priceRange: '€€',
    rating: 4.5,
    cover: '#F5FBF7',
    coverEmoji: '🥩',
    tags: ['Ménilmontant', 'Bistrot', 'Local'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/philoudarblay',
    description: 'Caché dans une rue discrète de Ménilmontant, Bistrot Darsy régale les habitués avec une cuisine de marché sans chichis et une atmosphère de vrai bistrot parisien populaire.',
    lat: 48.8648, lng: 2.3922,
  },
  {
    id: '20',
    name: 'Paul Chêne Cherche-Midi',
    cuisine: 'Française',
    city: 'Paris',
    address: '79 Rue du Cherche-Midi, 75006',
    priceRange: '€€€',
    rating: 4.7,
    cover: '#FDF0FD',
    coverEmoji: '🫕',
    tags: ['Gastronomique', 'Saint-Germain', 'Chef étoilé'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/philoudarblay',
    description: 'La table de Charles Laborde dans le 6e, une cuisine française précise et généreuse. Produits nobles travaillés avec finesse, carte courte qui change selon les saisons.',
    lat: 48.8479, lng: 2.3296,
  },
  {
    id: '21',
    name: 'Maison Baroche',
    cuisine: 'Française',
    city: 'Paris',
    address: '18 Rue Cadet, 75009',
    priceRange: '€€',
    rating: 4.6,
    cover: '#FDF8F4',
    coverEmoji: '🍽️',
    tags: ['Faubourg Montmartre', 'Bistronomique', 'Ardoise'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/philoudarblay',
    description: 'Une maison chaleureuse rue Cadet, entre Opéra et Montmartre. Cuisine bistronomique à l\'ardoise, produits sourcés avec soin et accueil aux petits oignons.',
    lat: 48.8757, lng: 2.3441,
  },
  {
    id: '22',
    name: 'Bon Vivant',
    cuisine: 'Française',
    city: 'Paris',
    address: '7 Rue des Écoles, 75005',
    priceRange: '€€',
    rating: 4.5,
    cover: '#ECF8F6',
    coverEmoji: '🥗',
    tags: ['Latin', 'Déjeuner', 'Terrasse'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/philoudarblay',
    description: 'En plein Quartier Latin, Bon Vivant incarne la brasserie de quartier idéale. Plats bistrotiers, belle cave et une terrasse agréable face à la vie du 5e.',
    lat: 48.8499, lng: 2.3522,
  },
  {
    id: '23',
    name: 'Chez Marcel',
    cuisine: 'Française',
    city: 'Paris',
    address: '7 Rue Stanislas, 75006',
    priceRange: '€€',
    rating: 4.6,
    cover: '#FFF8EC',
    coverEmoji: '🥘',
    tags: ['Bistrot classique', 'Lyonnais', 'Saint-Germain'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/philoudarblay',
    description: 'Un authentique bistrot lyonnais à Paris, repris par une famille passionnée. Tablier de sapeur, quenelles et pot de Beaujolais dans un décor rétro immuable.',
    lat: 48.8434, lng: 2.3325,
  },
  {
    id: '24',
    name: 'Épopée',
    cuisine: 'Française',
    city: 'Paris',
    address: '52 Rue Léon Frot, 75011',
    priceRange: '€€',
    rating: 4.7,
    cover: '#EBE9FA',
    coverEmoji: '✨',
    tags: ['Charonne', 'Néobistrot', 'Créatif'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/philoudarblay',
    description: 'L\'un des néobistrots phares du 11e. Cuisine inventive et généreuse, service décontracté et carte des vins nature soigneusement sélectionnée.',
    lat: 48.8567, lng: 2.3845,
  },
  {
    id: '25',
    name: 'Castille Paris',
    cuisine: 'Française',
    city: 'Paris',
    address: '33-37 Rue Cambon, 75001',
    priceRange: '€€€€',
    rating: 4.8,
    cover: '#FDF0FD',
    coverEmoji: '🏛️',
    tags: ['Palace', 'Luxe', 'Vendôme'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/philoudarblay',
    description: 'Le restaurant gastronomique de l\'hôtel Castille, à deux pas de la Place Vendôme. Cuisine française d\'exception dans un cadre élégant aux accents italiens.',
    lat: 48.8659, lng: 2.3266,
  },
  {
    id: '26',
    name: 'Restaurant Anne',
    cuisine: 'Française',
    city: 'Paris',
    address: '28 Place des Vosges, 75003',
    priceRange: '€€€',
    rating: 4.8,
    cover: '#ECF8F6',
    coverEmoji: '🏰',
    tags: ['Place des Vosges', 'Arcades', 'Gastronomique'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/philoudarblay',
    description: 'Sous les arcades de la plus belle place de Paris, Restaurant Anne propose une cuisine française raffinée dans un cadre historique inégalable. Vue imprenable sur la Place des Vosges.',
    lat: 48.8557, lng: 2.3623,
  },
  {
    id: '27',
    name: 'Eme Restaurant',
    cuisine: 'Française',
    city: 'Paris',
    address: '4 Impasse Guéménée, 75004',
    priceRange: '€€€',
    rating: 4.7,
    cover: '#FDF8F4',
    coverEmoji: '🌀',
    tags: ['Caché', 'Marais', 'Confidentiel'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/philoudarblay',
    description: 'Planqué dans une impasse du Marais, ce restaurant confidentiel réserve de belles surprises. Menu unique autour de produits d\'exception, cuisine ouverte sur la salle.',
    lat: 48.8536, lng: 2.3675,
  },
  {
    id: '28',
    name: 'Cypsele',
    cuisine: 'Grecque',
    city: 'Paris',
    address: '11 Rue des Deux Ponts, 75004',
    priceRange: '€€',
    rating: 4.6,
    cover: '#ECF8F6',
    coverEmoji: '🫒',
    tags: ['Île Saint-Louis', 'Grec contemporain', 'Mezze'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/philoudarblay',
    description: 'Une table grecque moderne sur l\'Île Saint-Louis. Mezze raffinés, poissons grillés et vins grecs naturels dans un décor épuré. Une adresse confidentielle très courue.',
    lat: 48.8520, lng: 2.3554,
  },
  {
    id: '29',
    name: 'Rôtisserie Segar',
    cuisine: 'Française',
    city: 'Paris',
    address: '111 Rue Mouffetard, 75005',
    priceRange: '€€',
    rating: 4.6,
    cover: '#FFF8EC',
    coverEmoji: '🍗',
    tags: ['Rôtisserie', 'Mouffetard', 'Volaille'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/philoudarblay',
    description: 'La rôtisserie de référence de la Rue Mouffetard. Poulets et pintades rôtis à la broche, pommes de terre fondantes et jus de cuisson doré. Simple, parfait.',
    lat: 48.8420, lng: 2.3509,
  },
  {
    id: '30',
    name: 'Le Petit Vendôme',
    cuisine: 'Française',
    city: 'Paris',
    address: '8 Rue des Capucines, 75002',
    priceRange: '€€',
    rating: 4.5,
    cover: '#F5FBF7',
    coverEmoji: '🥪',
    tags: ['Sandwich', 'Opéra', 'Bistrot'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/philoudarblay',
    description: 'Une institution du quartier Opéra, célèbre pour ses sandwichs maison et sa carte de bistrot immuable. Zinc, miroirs et habitués fidèles depuis des générations.',
    lat: 48.8697, lng: 2.3308,
  },
  {
    id: '31',
    name: 'Chez Georges',
    cuisine: 'Française',
    city: 'Paris',
    address: '1 Rue du Mail, 75002',
    priceRange: '€€€',
    rating: 4.8,
    cover: '#EBE9FA',
    coverEmoji: '🪄',
    tags: ['Institution', 'Classique', 'Bourse'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/philoudarblay',
    description: 'L\'une des grandes tables de bistrot parisien, ouverte depuis 1964. Steak tartare, sole meunière et crème caramel dans un décor à l\'ancienne d\'une authenticité rare.',
    lat: 48.8660, lng: 2.3469,
  },
  {
    id: '32',
    name: 'LAZU — Bouillon 47',
    cuisine: 'Française',
    city: 'Paris',
    address: '47 Rue Marguerite de Rochechouart, 75009',
    priceRange: '€',
    rating: 4.5,
    cover: '#FDF0FD',
    coverEmoji: '🫙',
    tags: ['Bouillon', 'Pigalle', 'Accessible'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/philoudarblay',
    description: 'Le bouillon populaire de Pigalle signé LAZU. Cuisine française traditionnelle à prix doux, œufs mayo, bœuf bourguignon et profiteroles dans une grande salle animée.',
    lat: 48.8798, lng: 2.3426,
  },
  {
    id: '33',
    name: 'Le Comptoir LAZU',
    cuisine: 'Française',
    city: 'Paris',
    address: '36 Rue Marguerite de Rochechouart, 75009',
    priceRange: '€',
    rating: 4.4,
    cover: '#FDF0FD',
    coverEmoji: '☕',
    tags: ['Comptoir', 'Pigalle', 'Déjeuner'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/philoudarblay',
    description: 'Le petit frère du Bouillon 47, en version comptoir et déjeuner rapide. Plat du jour, verre de vin et dessert maison — le ticket moyen le plus honnête du quartier.',
    lat: 48.8797, lng: 2.3420,
  },
  {
    id: '34',
    name: 'Le Mâche-Dru',
    cuisine: 'Française',
    city: 'Paris',
    address: '60 Rue Saint-Louis-en-l\'Île, 75004',
    priceRange: '€€',
    rating: 4.6,
    cover: '#F5FBF7',
    coverEmoji: '🏝️',
    tags: ['Île Saint-Louis', 'Bistrot', 'Marché'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/philoudarblay',
    description: 'Sur la rue principale de l\'Île Saint-Louis, ce bistrot attachant propose une cuisine de marché honnête loin du piège à touristes. Ambiance de village en plein Paris.',
    lat: 48.8514, lng: 2.3568,
  },
  {
    id: '35',
    name: 'L\'Entente — British Brasserie',
    cuisine: 'Britannique',
    city: 'Paris',
    address: '13 Rue Monsigny, 75002',
    priceRange: '€€',
    rating: 4.5,
    cover: '#ECF8F6',
    coverEmoji: '🫖',
    tags: ['British', 'Brunch', 'Opéra'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/philoudarblay',
    description: 'La cordiale entente franco-britannique dans l\'assiette. Fish & chips de poisson noble, Sunday roast et gin-tonics soignés dans un décor londonien assumé en plein Paris.',
    lat: 48.8700, lng: 2.3408,
  },
  {
    id: '36',
    name: 'La Maison de la Pistache',
    cuisine: 'Libanaise',
    city: 'Paris',
    address: '65 Rue du Bac, 75007',
    priceRange: '€',
    rating: 4.7,
    cover: '#F5FBF7',
    coverEmoji: '🟢',
    tags: ['Pistache', 'Libanais', 'Pâtisserie'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/philoudarblay',
    description: 'Le temple parisien de la pistache libanaise. Knafeh à la pistache, baklawa et croissant pistache-rose qui a fait le tour d\'Instagram. File d\'attente assurée le week-end.',
    lat: 48.8554, lng: 2.3250,
  },
  {
    id: '37',
    name: 'Arcane 17',
    cuisine: 'Française',
    city: 'Paris',
    address: '17 Rue Charlot, 75003',
    priceRange: '€€',
    rating: 4.6,
    cover: '#EBE9FA',
    coverEmoji: '🃏',
    tags: ['Haut Marais', 'Néobistrot', 'Naturel'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/philoudarblay',
    description: 'Une adresse à l\'image du Haut Marais : branchée, soignée et sans esbroufe. Cuisine de saison créative, belle liste de vins nature et salle lumineuse très cosy.',
    lat: 48.8625, lng: 2.3596,
  },
  {
    id: '38',
    name: 'Vivide',
    cuisine: 'Française',
    city: 'Paris',
    address: '3 Rue Dancourt, 75018',
    priceRange: '€€€',
    rating: 4.8,
    cover: '#FDF0FD',
    coverEmoji: '🎨',
    tags: ['Montmartre', 'Gastronomique', 'Créatif'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/philoudarblay',
    description: 'À deux pas du Moulin Rouge, Vivide propose une cuisine gastronomique française d\'une rare créativité. Menu dégustation en constante évolution, produits d\'exception et service attentionné.',
    lat: 48.8841, lng: 2.3488,
  },
  {
    id: '39',
    name: 'Quedubon',
    cuisine: 'Française',
    city: 'Paris',
    address: '22 Rue du Plateau, 75019',
    priceRange: '€€',
    rating: 4.7,
    cover: '#F5FBF7',
    coverEmoji: '🍾',
    tags: ['Buttes-Chaumont', 'Cave à manger', 'Nature'],
    recommendedBy: { handle: '@theovoyageyrgourmand', name: 'Théo, Voyageur Gourmand', followers: '185K', avatar: '🧑‍🍳' },
    instagramPost: 'https://www.instagram.com/theovoyageyrgourmand',
    description: 'La cave à manger de référence des Buttes-Chaumont. Sélection pointue de vins naturels, assiettes généreuses de charcuterie et fromages affinés dans un quartier devenu très couru.',
    lat: 48.8814, lng: 2.3727,
  },
  {
    id: '40',
    name: 'Le Baratin',
    cuisine: 'Française',
    city: 'Paris',
    address: '3 Rue Jouye-Rouve, 75020',
    priceRange: '€€',
    rating: 4.8,
    cover: '#EBE9FA',
    coverEmoji: '🍷',
    tags: ['Belleville', 'Vin nature', 'Bistrot culte'],
    recommendedBy: { handle: '@theovoyageyrgourmand', name: 'Théo, Voyageur Gourmand', followers: '185K', avatar: '🧑‍🍳' },
    instagramPost: 'https://www.instagram.com/theovoyageyrgourmand',
    description: 'Une institution du vin nature à Belleville. Raquel Carena tient cette cave à manger depuis des décennies, réputée pour sa sélection pointue et sa cuisine franche du collier.',
    lat: 48.8726, lng: 2.3903,
  },
  {
    id: '41',
    name: 'Patine',
    cuisine: 'Française',
    city: 'Paris',
    address: '16 Rue la Vacquerie, 75011',
    priceRange: '€€€',
    rating: 4.7,
    cover: '#FDF8F4',
    coverEmoji: '🕯️',
    tags: ['Bistronomique', 'Oberkampf', 'Créatif'],
    recommendedBy: { handle: '@theovoyageyrgourmand', name: 'Théo, Voyageur Gourmand', followers: '185K', avatar: '🧑‍🍳' },
    instagramPost: 'https://www.instagram.com/theovoyageyrgourmand',
    description: 'Une adresse discrète du 11e qui mise sur une cuisine fine et créative. Carte courte, produits travaillés avec soin, atmosphère intime et chaleureuse.',
    lat: 48.8553, lng: 2.3810,
  },
  {
    id: '42',
    name: 'Gramme',
    cuisine: 'Française',
    city: 'Paris',
    address: '96 Rue Jean-Pierre Timbaud, 75011',
    priceRange: '€',
    rating: 4.5,
    cover: '#F5FBF7',
    coverEmoji: '☕',
    tags: ['Café', 'Brunch', 'Timbaud'],
    recommendedBy: { handle: '@theovoyageyrgourmand', name: 'Théo, Voyageur Gourmand', followers: '185K', avatar: '🧑‍🍳' },
    instagramPost: 'https://www.instagram.com/theovoyageyrgourmand',
    description: 'Le café de quartier idéal de la rue Timbaud. Brunch soigné, viennoiseries maison et carte simple mais impeccable dans un espace lumineux très Oberkampf.',
    lat: 48.8657, lng: 2.3762,
  },
  {
    id: '43',
    name: 'Erso',
    cuisine: 'Française',
    city: 'Paris',
    address: '18 Rue Saint-Ambroise, 75011',
    priceRange: '€€',
    rating: 4.6,
    cover: '#ECF8F6',
    coverEmoji: '🌾',
    tags: ['Naturel', '11e', 'Ardoise'],
    recommendedBy: { handle: '@theovoyageyrgourmand', name: 'Théo, Voyageur Gourmand', followers: '185K', avatar: '🧑‍🍳' },
    instagramPost: 'https://www.instagram.com/theovoyageyrgourmand',
    description: 'Un bistrot naturel ancré dans le 11e, fidèle aux producteurs locaux et aux vins sans soufre. Menu du marché à l\'ardoise, ambiance décontractée et généreuse.',
    lat: 48.8624, lng: 2.3769,
  },
  {
    id: '44',
    name: 'Slak Paris',
    cuisine: 'Française',
    city: 'Paris',
    address: '27 Rue Pierre Fontaine, 75009',
    priceRange: '€€',
    rating: 4.5,
    cover: '#FDF0FD',
    coverEmoji: '🎵',
    tags: ['Pigalle', 'Cocktails', 'Festif'],
    recommendedBy: { handle: '@theovoyageyrgourmand', name: 'Théo, Voyageur Gourmand', followers: '185K', avatar: '🧑‍🍳' },
    instagramPost: 'https://www.instagram.com/theovoyageyrgourmand',
    description: 'En plein Pigalle, Slak conjugue bonne cuisine et ambiance musicale. Plats généreux à partager, cocktails créatifs et salle qui monte en puissance en soirée.',
    lat: 48.8824, lng: 2.3347,
  },
  {
    id: '45',
    name: 'Lacigne',
    cuisine: 'Française',
    city: 'Paris',
    address: '124 Avenue Parmentier, 75011',
    priceRange: '€€',
    rating: 4.6,
    cover: '#FFF8EC',
    coverEmoji: '🦢',
    tags: ['Parmentier', 'Bistronomique', 'Cave'],
    recommendedBy: { handle: '@theovoyageyrgourmand', name: 'Théo, Voyageur Gourmand', followers: '185K', avatar: '🧑‍🍳' },
    instagramPost: 'https://www.instagram.com/theovoyageyrgourmand',
    description: 'Une table soignée avenue Parmentier, entre bistrot et cave à manger. Cuisine française précise, belle sélection de vins naturels et service attentionné.',
    lat: 48.8641, lng: 2.3795,
  },
  {
    id: '46',
    name: 'Dents de Loup',
    cuisine: 'Française',
    city: 'Paris',
    address: '75 Rue Marguerite de Rochechouart, 75009',
    priceRange: '€€',
    rating: 4.6,
    cover: '#EBE9FA',
    coverEmoji: '🐺',
    tags: ['Pigalle', 'Bistrot', 'Vin nature'],
    recommendedBy: { handle: '@theovoyageyrgourmand', name: 'Théo, Voyageur Gourmand', followers: '185K', avatar: '🧑‍🍳' },
    instagramPost: 'https://www.instagram.com/theovoyageyrgourmand',
    description: 'Bistrot nature à deux pas de Pigalle. Petite carte qui change selon les arrivages, vins vivants et atmosphère de cave chaleureuse très appréciée des habitués.',
    lat: 48.8822, lng: 2.3466,
  },
  {
    id: '47',
    name: 'Pastasuta Poissonière',
    cuisine: 'Italienne',
    city: 'Paris',
    address: '9 Rue du Faubourg Poissonnière, 75009',
    priceRange: '€',
    rating: 4.7,
    cover: '#FDF8F4',
    coverEmoji: '🍝',
    tags: ['Pasta fraîche', 'Faubourg', 'Rapide'],
    recommendedBy: { handle: '@theovoyageyrgourmand', name: 'Théo, Voyageur Gourmand', followers: '185K', avatar: '🧑‍🍳' },
    instagramPost: 'https://www.instagram.com/theovoyageyrgourmand',
    description: 'Pâtes fraîches préparées sous vos yeux, sauces généreuses et prix doux. Le spot parfait pour un déjeuner rapide et authentique à deux pas des Grands Boulevards.',
    lat: 48.8736, lng: 2.3493,
  },
  {
    id: '48',
    name: 'Tuan Paris',
    cuisine: 'Vietnamienne',
    city: 'Paris',
    address: '24 Rue de Babylone, 75007',
    priceRange: '€€',
    rating: 4.7,
    cover: '#F5FBF7',
    coverEmoji: '🍜',
    tags: ['Vietnamien', 'Saint-Germain', 'Gastronomique'],
    recommendedBy: { handle: '@theovoyageyrgourmand', name: 'Théo, Voyageur Gourmand', followers: '185K', avatar: '🧑‍🍳' },
    instagramPost: 'https://www.instagram.com/theovoyageyrgourmand',
    description: 'La cuisine vietnamienne gastronomique du 7e. Pho de bœuf longuement mijoté, rouleaux de printemps maison et bo bun parfumé dans un cadre élégant et feutré.',
    lat: 48.8524, lng: 2.3214,
  },
  {
    id: '49',
    name: 'Restaurant Irwin',
    cuisine: 'Française',
    city: 'Paris',
    address: '22 Rue Cambacérès, 75008',
    priceRange: '€€€',
    rating: 4.7,
    cover: '#ECF8F6',
    coverEmoji: '🌿',
    tags: ['8e', 'Gastronomique', 'Élégant'],
    recommendedBy: { handle: '@theovoyageyrgourmand', name: 'Théo, Voyageur Gourmand', followers: '185K', avatar: '🧑‍🍳' },
    instagramPost: 'https://www.instagram.com/theovoyageyrgourmand',
    description: 'Une table gastronomique discrète dans le 8e. Cuisine française contemporaine, produits d\'exception et service impeccable dans un décor sobre et raffiné.',
    lat: 48.8745, lng: 2.3152,
  },
  {
    id: '50',
    name: 'Restaurant Alliance',
    cuisine: 'Française',
    city: 'Paris',
    address: '5 Rue de Poissy, 75005',
    priceRange: '€€€€',
    rating: 4.9,
    cover: '#FDF0FD',
    coverEmoji: '⭐',
    tags: ['Étoilé', 'Gastronomique', 'Latin'],
    recommendedBy: { handle: '@theovoyageyrgourmand', name: 'Théo, Voyageur Gourmand', followers: '185K', avatar: '🧑‍🍳' },
    instagramPost: 'https://www.instagram.com/theovoyageyrgourmand',
    description: 'Table étoilée du Quartier Latin, tenue par Thibaut Spiwack. Cuisine végétale et durable d\'une finesse remarquable, engagée dans une démarche environnementale exemplaire.',
    lat: 48.8507, lng: 2.3529,
  },
  {
    id: '51',
    name: 'Le Pigeon de Dandelion',
    cuisine: 'Française',
    city: 'Paris',
    address: '46 Rue des Vignoles, 75020',
    priceRange: '€€',
    rating: 4.6,
    cover: '#FDF8F4',
    coverEmoji: '🕊️',
    tags: ['Charonne', 'Créatif', 'Confidentiel'],
    recommendedBy: { handle: '@theovoyageyrgourmand', name: 'Théo, Voyageur Gourmand', followers: '185K', avatar: '🧑‍🍳' },
    instagramPost: 'https://www.instagram.com/theovoyageyrgourmand',
    description: 'Planqué dans la rue des Vignoles, ce bistrot créatif mise sur des associations inattendues et des produits sourcés avec soin. Une adresse confidentielle qui mérite le détour.',
    lat: 48.8590, lng: 2.3990,
  },
  {
    id: '52',
    name: 'Paul Bert',
    cuisine: 'Française',
    city: 'Paris',
    address: '18 Rue Paul Bert, 75011',
    priceRange: '€€€',
    rating: 4.8,
    cover: '#EBE9FA',
    coverEmoji: '🥩',
    tags: ['Bistrot classique', 'Faubourg Saint-Antoine', 'Institution'],
    recommendedBy: { handle: '@theovoyageyrgourmand', name: 'Théo, Voyageur Gourmand', followers: '185K', avatar: '🧑‍🍳' },
    instagramPost: 'https://www.instagram.com/theovoyageyrgourmand',
    description: 'L\'un des grands bistrots parisiens, véritable institution du Faubourg Saint-Antoine. Entrecôte Café de Paris, tarte tatin et cave à vins de collection dans un décor immuable.',
    lat: 48.8524, lng: 2.3868,
  },
  {
    id: '53',
    name: 'Tsukizi',
    cuisine: 'Japonaise',
    city: 'Paris',
    address: '2 Bis Rue des Ciseaux, 75006',
    priceRange: '€€',
    rating: 4.7,
    cover: '#FDF0FD',
    coverEmoji: '🍱',
    tags: ['Sushi', 'Saint-Germain', 'Authentique'],
    recommendedBy: { handle: '@theovoyageyrgourmand', name: 'Théo, Voyageur Gourmand', followers: '185K', avatar: '🧑‍🍳' },
    instagramPost: 'https://www.instagram.com/theovoyageyrgourmand',
    description: 'Petit comptoir japonais confidentiel à Saint-Germain. Sushis et sashimis d\'une fraîcheur irréprochable, préparés devant vous par un chef formé au Japon. Réservation vivement conseillée.',
    lat: 48.8532, lng: 2.3364,
  },
  {
    id: '54',
    name: 'Tara Café Vin',
    cuisine: 'Française',
    city: 'Paris',
    address: '2 Rue de la Fontaine au Roi, 75011',
    priceRange: '€€',
    rating: 4.6,
    cover: '#F5FBF7',
    coverEmoji: '🫗',
    tags: ['Cave à manger', 'Fontaine au Roi', 'Nature'],
    recommendedBy: { handle: '@theovoyageyrgourmand', name: 'Théo, Voyageur Gourmand', followers: '185K', avatar: '🧑‍🍳' },
    instagramPost: 'https://www.instagram.com/theovoyageyrgourmand',
    description: 'Cave à manger chaleureuse à l\'entrée du 11e. Vins naturels de petits vignerons, assiettes à partager généreuses et ambiance de comptoir qui donne envie de s\'attarder.',
    lat: 48.8670, lng: 2.3638,
  },
  {
    id: '55',
    name: 'Maison Rostang',
    cuisine: 'Française',
    city: 'Paris',
    address: '20 Rue Rennequin, 75017',
    priceRange: '€€€€',
    rating: 4.9,
    cover: '#FDF0FD',
    coverEmoji: '⭐',
    tags: ['2 étoiles Michelin', 'Gastronomique', 'Ternes'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/p/DLFmPB8iWKZ/',
    description: 'La grande maison de Michel Rostang, deux étoiles Michelin depuis des décennies. Cuisine française d\'exception, service impeccable et cadre bourgeois raffiné dans le 17e.',
    lat: 48.8806, lng: 2.2996,
  },
  {
    id: '56',
    name: 'Biche Paris',
    cuisine: 'Française',
    city: 'Paris',
    address: '129 Rue du Faubourg Saint-Honoré, 75008',
    priceRange: '€€€',
    rating: 4.7,
    cover: '#ECF8F6',
    coverEmoji: '🦌',
    tags: ['Faubourg Saint-Honoré', 'Chic', 'Bistronomique'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/leparisdalexis',
    description: 'Une adresse élégante du Faubourg Saint-Honoré, entre brasserie chic et bistrot gastronomique. Cuisine française soignée dans un décor lumineux très apprécié des habitués du quartier.',
    lat: 48.8739, lng: 2.3075,
  },
  {
    id: '57',
    name: 'Ô\'Cocher',
    cuisine: 'Française',
    city: 'Paris',
    address: '45 Rue de Babylone, 75007',
    priceRange: '€€',
    rating: 4.6,
    cover: '#FFF8EC',
    coverEmoji: '🐎',
    tags: ['7e', 'Bistrot', 'Quartier'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/leparisdalexis',
    description: 'Le bistrot de quartier du 7e qui régale les riverains comme les touristes égarés. Cuisine française simple et généreuse, carte courte bien ficelée et service souriant.',
    lat: 48.8516, lng: 2.3210,
  },
  {
    id: '58',
    name: 'Braise',
    cuisine: 'Française',
    city: 'Paris',
    address: '19 Rue d\'Anjou, 75008',
    priceRange: '€€€',
    rating: 4.7,
    cover: '#FFF8EC',
    coverEmoji: '🔥',
    tags: ['Grill', 'Viande', 'Madeleine'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/leparisdalexis',
    description: 'La table du feu de bois dans le 8e. Viandes et légumes cuits à la braise, fumés avec précision par un chef maîtrisant la cuisson au charbon de bois comme peu savent le faire à Paris.',
    lat: 48.8752, lng: 2.3237,
  },
  {
    id: '59',
    name: 'Vida\'M',
    cuisine: 'Française',
    city: 'Paris',
    address: '34 Rue de Cambrai, 75019',
    priceRange: '€€',
    rating: 4.5,
    cover: '#F5FBF7',
    coverEmoji: '🌈',
    tags: ['19e', 'Fusion', 'Contemporain'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/leparisdalexis',
    description: 'Une adresse dynamique du 19e qui mêle influences françaises et internationales. Cuisine créative aux influences multiples, cadre convivial et carte de vins accessible.',
    lat: 48.8924, lng: 2.3687,
  },
  {
    id: '60',
    name: 'Pocha',
    cuisine: 'Coréenne',
    city: 'Paris',
    address: '82 Boulevard du Montparnasse, 75014',
    priceRange: '€€',
    rating: 4.6,
    cover: '#FDF8F4',
    coverEmoji: '🍶',
    tags: ['Pocha', 'Coréen', 'Montparnasse'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/leparisdalexis',
    description: 'L\'esprit des bars à snacks coréens au pied du Montparnasse. Pancakes coréens, poulet frit épicé et soju en pichet dans une ambiance festive et décontractée.',
    lat: 48.8431, lng: 2.3262,
  },
  {
    id: '61',
    name: 'Pocha',
    cuisine: 'Coréenne',
    city: 'Paris',
    address: '21 Rue Saint-Augustin, 75002',
    priceRange: '€€',
    rating: 4.6,
    cover: '#FDF8F4',
    coverEmoji: '🍶',
    tags: ['Pocha', 'Coréen', 'Opéra'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/leparisdalexis',
    description: 'La deuxième adresse Pocha, côté Opéra. Même ambiance pocha, mêmes classiques coréens à partager — tteokbokki, pajeon et makgeolli — dans un quartier plus central.',
    lat: 48.8694, lng: 2.3359,
  },
  {
    id: '62',
    name: 'Rotisserie Cotcotgardette',
    cuisine: 'Française',
    city: 'Paris',
    address: '22 Rue Rochebrune, 75011',
    priceRange: '€€',
    rating: 4.6,
    cover: '#FFF8EC',
    coverEmoji: '🍗',
    tags: ['Rôtisserie', 'Voltaire', 'Volaille'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/leparisdalexis',
    description: 'La rôtisserie du quartier Voltaire. Poulets fermiers et légumes rôtis à la broche, jus de cuisson doré servi en saucière. Simple, honnête et délicieux.',
    lat: 48.8552, lng: 2.3793,
  },
  {
    id: '63',
    name: 'Pâtisserie Adroyte',
    cuisine: 'Française',
    city: 'Paris',
    address: '14 Rue Froissart, 75003',
    priceRange: '€',
    rating: 4.7,
    cover: '#FDF0FD',
    coverEmoji: '🧁',
    tags: ['Pâtisserie', 'Marais', 'Créatif'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/leparisdalexis',
    description: 'La pâtisserie créative du Haut Marais. Tartes, entremets et viennoiseries à l\'esthétique soignée qui font le tour d\'Instagram avant d\'être dévorés avec délectation.',
    lat: 48.8613, lng: 2.3616,
  },
  {
    id: '64',
    name: 'BOULOM',
    cuisine: 'Française',
    city: 'Paris',
    address: '181 Rue Ordener, 75018',
    priceRange: '€',
    rating: 4.7,
    cover: '#F5FBF7',
    coverEmoji: '🥐',
    tags: ['Boulangerie', 'Montmartre', 'Artisanal'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/leparisdalexis',
    description: 'La boulangerie de référence du bas Montmartre. Pain au levain, croissants feuilletés et sandwichs généreux — une adresse de quartier qui a su devenir une institution.',
    lat: 48.8931, lng: 2.3461,
  },
  {
    id: '65',
    name: 'Libeyrouth',
    cuisine: 'Libanaise',
    city: 'Paris',
    address: '72 Rue Mouffetard, 75005',
    priceRange: '€€',
    rating: 4.7,
    cover: '#FDF8F4',
    coverEmoji: '🧆',
    tags: ['Libanais', 'Mouffetard', 'Mezze'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/leparisdalexis',
    description: 'L\'adresse libanaise incontournable de la Rue Mouffetard. Houmous maison, kibbeh et falafels croustillants — une cuisine familiale authentique dans un décor chaleureux.',
    lat: 48.8440, lng: 2.3502,
  },
  {
    id: '66',
    name: 'Kasumi',
    cuisine: 'Japonaise',
    city: 'Paris',
    address: '47 Rue de Richelieu, 75001',
    priceRange: '€€€',
    rating: 4.8,
    cover: '#ECF8F6',
    coverEmoji: '🍱',
    tags: ['Japonais', 'Palais-Royal', 'Kaiseki'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/leparisdalexis',
    description: 'Cuisine japonaise raffinée à deux pas du Palais-Royal. Menu dégustation inspiré du kaiseki, produits franco-japonais d\'exception et atmosphère zen pour une expérience hors du commun.',
    lat: 48.8648, lng: 2.3378,
  },
  {
    id: '67',
    name: 'Navigli Aperitivo',
    cuisine: 'Italienne',
    city: 'Paris',
    address: '52 Rue d\'Enghien, 75010',
    priceRange: '€€',
    rating: 4.5,
    cover: '#FDF0FD',
    coverEmoji: '🍹',
    tags: ['Aperitivo', 'Milan', 'Cocktails'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/leparisdalexis',
    description: 'L\'esprit des Navigli milanais transposé à Paris. Spritz, Negroni et buffet d\'aperitivo généreux à l\'heure de l\'apéro — une parenthèse italienne dans le 10e.',
    lat: 48.8737, lng: 2.3520,
  },
  {
    id: '68',
    name: 'Doma Paris',
    cuisine: 'Coréenne',
    city: 'Paris',
    address: '11 Rue Godot de Mauroy, 75009',
    priceRange: '€€',
    rating: 4.6,
    cover: '#EBE9FA',
    coverEmoji: '🥢',
    tags: ['Coréen', 'Opéra', 'Moderne'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/leparisdalexis',
    description: 'Cuisine coréenne contemporaine dans le 9e. Bibimbap signature, japchae maison et makgeolli en cruche dans un décor épuré qui fait la part belle aux produits frais.',
    lat: 48.8748, lng: 2.3351,
  },
  {
    id: '69',
    name: 'Pastasuta',
    cuisine: 'Italienne',
    city: 'Paris',
    address: '2 Rue de la Coutellerie, 75004',
    priceRange: '€',
    rating: 4.7,
    cover: '#FDF8F4',
    coverEmoji: '🍝',
    tags: ['Pasta fraîche', 'Hôtel de Ville', 'Rapide'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/leparisdalexis',
    description: 'Pâtes fraîches roulées sous vos yeux près de l\'Hôtel de Ville. Carbonara, cacio e pepe et pesto maison — la recette du succès tient en trois ingrédients et beaucoup de savoir-faire.',
    lat: 48.8567, lng: 2.3493,
  },
  {
    id: '70',
    name: 'Kushikatsubon Paris',
    cuisine: 'Japonaise',
    city: 'Paris',
    address: '24 Rue Jean-Pierre Timbaud, 75011',
    priceRange: '€€',
    rating: 4.6,
    cover: '#FFF8EC',
    coverEmoji: '🍡',
    tags: ['Kushikatsu', 'Timbaud', 'Friture japonaise'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/leparisdalexis',
    description: 'Le seul restaurant spécialisé en kushikatsu de Paris — brochettes panées et frites originaires d\'Osaka. Viandes, légumes et fruits de mer en croûte légère, sauce maison interdite de double trempage.',
    lat: 48.8634, lng: 2.3742,
  },
  {
    id: '71',
    name: 'Black Angus',
    cuisine: 'Américaine',
    city: 'Paris',
    address: '8 Place de la République, 75011',
    priceRange: '€€€',
    rating: 4.6,
    cover: '#EBE9FA',
    coverEmoji: '🥩',
    tags: ['Steakhouse', 'République', 'Black Angus'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/leparisdalexis',
    description: 'Le steakhouse américain de référence place de la République. Bœuf Black Angus maturé, cuisson à la braise au charbon de bois et sauces maison pour les amateurs de viande exigeants.',
    lat: 48.8676, lng: 2.3635,
  },
  {
    id: '72',
    name: 'Black Angus',
    cuisine: 'Américaine',
    city: 'Paris',
    address: '96 Rue Saint-Lazare, 75009',
    priceRange: '€€€',
    rating: 4.6,
    cover: '#EBE9FA',
    coverEmoji: '🥩',
    tags: ['Steakhouse', 'Saint-Lazare', 'Black Angus'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/leparisdalexis',
    description: 'La deuxième adresse Black Angus côté Saint-Lazare. Même engagement sur la qualité de la viande et les cuissons maîtrisées, idéalement situé pour un dîner après le bureau.',
    lat: 48.8780, lng: 2.3329,
  },
  {
    id: '73',
    name: 'Khunakorn',
    cuisine: 'Thaïlandaise',
    city: 'Paris',
    address: '8 Avenue de Taillebourg, 75011',
    priceRange: '€€',
    rating: 4.7,
    cover: '#F5FBF7',
    coverEmoji: '🌶️',
    tags: ['Thaï', 'Nation', 'Authentique'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/leparisdalexis',
    description: 'La table thaïlandaise la plus authentique du 11e. Curry massaman, pad thaï à la crevette et som tam préparés par une équipe thaïe qui ne fait aucune concession sur les épices.',
    lat: 48.8535, lng: 2.3883,
  },
  {
    id: '74',
    name: 'Bomaye Club',
    cuisine: 'Française',
    city: 'Paris',
    address: '16 Rue de Paradis, 75010',
    priceRange: '€€',
    rating: 4.5,
    cover: '#FDF0FD',
    coverEmoji: '🎤',
    tags: ['10e', 'Bar à dîner', 'Festif'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/leparisdalexis',
    description: 'Bar-restaurant festif rue de Paradis. Cuisine généreuse à partager, cocktails bien dosés et ambiance qui monte en puissance au fil de la soirée — le spot parfait avant une nuit dans le 10e.',
    lat: 48.8756, lng: 2.3512,
  },
  {
    id: '75',
    name: 'Casimir',
    cuisine: 'Française',
    city: 'Paris',
    address: '6 Rue de Belzunce, 75010',
    priceRange: '€€',
    rating: 4.6,
    cover: '#ECF8F6',
    coverEmoji: '🍺',
    tags: ['Bistrot', 'Château d\'Eau', 'Populaire'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/leparisdalexis',
    description: 'Un bistrot populaire et sans chichis près du Château d\'Eau. Plats généreux à prix doux, cave honnête et terrasse animée qui reflète bien l\'énergie de ce quartier en pleine effervescence.',
    lat: 48.8767, lng: 2.3542,
  },
  {
    id: '76',
    name: 'Oh My Jerk',
    cuisine: 'Antillaise',
    city: 'Paris',
    address: '3 Rue Eugène Varlin, 75010',
    priceRange: '€',
    rating: 4.6,
    cover: '#FFF8EC',
    coverEmoji: '🍖',
    tags: ['Jerk', 'Jamaïcain', 'Street food'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/leparisdalexis',
    description: 'Le meilleur jerk de Paris, rien que ça. Poulet et porc marinés aux épices jamaïcaines, cuits lentement sur charbon de bois — une explosion de saveurs pour quelques euros seulement.',
    lat: 48.8719, lng: 2.3630,
  },
  {
    id: '77',
    name: 'Qasti Bistrot',
    cuisine: 'Française',
    city: 'Paris',
    address: '205 Rue Saint-Martin, 75003',
    priceRange: '€€',
    rating: 4.5,
    cover: '#FDF8F4',
    coverEmoji: '🌍',
    tags: ['Fusion', 'Beaubourg', 'Créatif'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/leparisdalexis',
    description: 'Bistrot aux influences méditerranéennes et moyen-orientales près de Beaubourg. Cuisine créative qui voyage entre Paris et les épices du Levant, dans un cadre chaleureux et accessible.',
    lat: 48.8637, lng: 2.3543,
  },
  {
    id: '78',
    name: 'La Foccacceria',
    cuisine: 'Italienne',
    city: 'Paris',
    address: '104 Rue du Faubourg Poissonnière, 75010',
    priceRange: '€',
    rating: 4.6,
    cover: '#FDF0FD',
    coverEmoji: '🫓',
    tags: ['Focaccia', 'Italien', 'Faubourg'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/leparisdalexis',
    description: 'Focacce garnies à la ligurienne, préparées chaque matin dans des moules dorés. Garnitures généreuses, pain moelleux et croustillant — la pause déjeuner idéale du Faubourg Poissonnière.',
    lat: 48.8747, lng: 2.3493,
  },
  {
    id: '79',
    name: 'Jjin',
    cuisine: 'Coréenne',
    city: 'Paris',
    address: '35 Rue du Faubourg Saint-Denis, 75010',
    priceRange: '€€',
    rating: 4.6,
    cover: '#EBE9FA',
    coverEmoji: '♨️',
    tags: ['Coréen', 'Saint-Denis', 'Vapeur'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/leparisdalexis',
    description: 'Spécialiste du jjin — cuisson vapeur coréenne — dans l\'animation du Faubourg Saint-Denis. Mandu vapeur, poulet jjimdak et soupes réconfortantes servies dans un décor épuré.',
    lat: 48.8714, lng: 2.3552,
  },
  {
    id: '80',
    name: 'Drouant',
    cuisine: 'Française',
    city: 'Paris',
    address: '16-18 Place Gaillon, 75002',
    priceRange: '€€€€',
    rating: 4.8,
    cover: '#ECF8F6',
    coverEmoji: '🏛️',
    tags: ['Institution', 'Prix Goncourt', 'Gastronomique'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/leparisdalexis',
    description: 'L\'institution parisienne où le Prix Goncourt est décerné chaque année depuis 1914. Cuisine française de haute volée dans un décor Art déco somptueux, entre histoire et gastronomie.',
    lat: 48.8694, lng: 2.3392,
  },
  {
    id: '81',
    name: 'Chakaiseki Akiyoshi',
    cuisine: 'Japonaise',
    city: 'Paris',
    address: '59 Rue Letellier, 75015',
    priceRange: '€€€',
    rating: 4.8,
    cover: '#FDF0FD',
    coverEmoji: '🍵',
    tags: ['Kaiseki', 'Cérémonie du thé', 'Gastronomique'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/leparisdalexis',
    description: 'L\'unique restaurant de chakaiseki en Europe — cuisine japonaise inspirée de la cérémonie du thé. Une expérience sensorielle d\'une rare poésie, portée par le chef Akiyoshi dans le calme du 15e.',
    lat: 48.8417, lng: 2.2985,
  },
  {
    id: '82',
    name: 'Rednoodle',
    cuisine: 'Chinoise',
    city: 'Paris',
    address: '23 Boulevard des Italiens, 75002',
    priceRange: '€€',
    rating: 4.5,
    cover: '#FFF8EC',
    coverEmoji: '🍜',
    tags: ['Nouilles', 'Grands Boulevards', 'Wok'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/leparisdalexis',
    description: 'Nouilles chinoises tirées à la main sur les Grands Boulevards. Bouillons intenses, garnitures généreuses et cuisson au wok — une adresse qui casse les idées reçues sur la cuisine chinoise à Paris.',
    lat: 48.8710, lng: 2.3379,
  },
  {
    id: '83',
    name: 'BricktoPizza',
    cuisine: 'Italienne',
    city: 'Paris',
    address: '153 Quai de Valmy, 75010',
    priceRange: '€€',
    rating: 4.6,
    cover: '#FDF8F4',
    coverEmoji: '🍕',
    tags: ['Pizza', 'Canal Saint-Martin', 'Four à bois'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/leparisdalexis',
    description: 'Pizzas cuites au four à brique face au Canal Saint-Martin. Pâte légèrement soufflée, garnitures généreuses et vue sur le canal — l\'adresse pizza incontournable du 10e.',
    lat: 48.8742, lng: 2.3650,
  },
  {
    id: '84',
    name: 'One and One',
    cuisine: 'Italienne',
    city: 'Paris',
    address: '7 Passage des Panoramas, 75002',
    priceRange: '€€',
    rating: 4.6,
    cover: '#ECF8F6',
    coverEmoji: '🫱🏼‍🫲🏼',
    tags: ['Passage couvert', 'Italian', 'Ambiance'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/leparisdalexis',
    description: 'Une table italienne nichée dans le mythique Passage des Panoramas. Antipasti, pastas fraîches et tiramisu maison dans un cadre historique chargé d\'une atmosphère unique.',
    lat: 48.8702, lng: 2.3454,
  },
  {
    id: '85',
    name: 'Il Était Un Square',
    cuisine: 'Française',
    city: 'Paris',
    address: '54 Rue Corvisart, 75013',
    priceRange: '€€',
    rating: 4.6,
    cover: '#F5FBF7',
    coverEmoji: '🌳',
    tags: ['Butte-aux-Cailles', 'Bistrot', 'Verdure'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/leparisdalexis',
    description: 'Un bistrot vert et chaleureux à deux pas de la Butte-aux-Cailles. Cuisine du marché honnête, belle sélection de vins nature et terrasse sur le square pour les beaux jours.',
    lat: 48.8323, lng: 2.3506,
  },
  {
    id: '86',
    name: 'Restaurant N+1',
    cuisine: 'Française',
    city: 'Paris',
    address: '151 Rue du Chevaleret, 75013',
    priceRange: '€€',
    rating: 4.6,
    cover: '#EBE9FA',
    coverEmoji: '🔬',
    tags: ['Chevaleret', 'Créatif', 'Confidentiel'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/leparisdalexis',
    description: 'Une table confidentielle dans le quartier des anciens entrepôts du 13e. Cuisine créative et précise, menu unique qui évolue selon les saisons et l\'humeur du chef.',
    lat: 48.8282, lng: 2.3665,
  },
  {
    id: '87',
    name: 'Les Frérots Paris',
    cuisine: 'Française',
    city: 'Paris',
    address: '117 Rue des Dames, 75017',
    priceRange: '€€',
    rating: 4.5,
    cover: '#FFF8EC',
    coverEmoji: '👬',
    tags: ['Batignolles', 'Bistrot', 'Convivial'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/leparisdalexis',
    description: 'Le bistrot convivial des Batignolles tenu par deux frères. Cuisine française généreuse et sans fioritures, plats du marché à l\'ardoise et ambiance de quartier irréprochable.',
    lat: 48.8847, lng: 2.3216,
  },
  {
    id: '88',
    name: 'Pâtisserie Melitot',
    cuisine: 'Française',
    city: 'Paris',
    address: '50 Rue de la Réunion, 75020',
    priceRange: '€',
    rating: 4.7,
    cover: '#FDF0FD',
    coverEmoji: '🌸',
    tags: ['Pâtisserie', '20e', 'Créatif'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/leparisdalexis',
    description: 'La pâtisserie créative du 20e qui fait parler d\'elle bien au-delà du quartier. Entremets floraux, tartes aux saveurs audacieuses et viennoiseries qui disparaissent dès l\'ouverture.',
    lat: 48.8617, lng: 2.4024,
  },
  {
    id: '89',
    name: 'Biwan Irasshai',
    cuisine: 'Japonaise',
    city: 'Paris',
    address: '40 Rue du Louvre, 75001',
    priceRange: '€€€',
    rating: 4.7,
    cover: '#ECF8F6',
    coverEmoji: '🏮',
    tags: ['Japonais', 'Louvre', 'Izakaya'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/leparisdalexis',
    description: 'Izakaya japonais soigné face au Louvre. Yakitori de volaille fermière, gyoza maison et saké de qualité dans une atmosphère intimiste très éloignée des clichés de la cuisine nippone à Paris.',
    lat: 48.8623, lng: 2.3445,
  },
  {
    id: '90',
    name: 'Café de la Paix',
    cuisine: 'Française',
    city: 'Paris',
    address: '5 Place de l\'Opéra, 75009',
    priceRange: '€€€€',
    rating: 4.7,
    cover: '#EBE9FA',
    coverEmoji: '🎭',
    tags: ['Institution', 'Opéra', 'Classé'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/leparisdalexis',
    description: 'Monument historique classé, ouvert en 1862, face à l\'Opéra Garnier. Décor Second Empire somptueux, cuisine française grand-siècle et terrasse sur la Place de l\'Opéra pour observer le monde défiler.',
    lat: 48.8710, lng: 2.3310,
  },
  {
    id: '91',
    name: 'Osanchaise',
    cuisine: 'Française',
    city: 'Paris',
    address: '3 Rue Papillon, 75009',
    priceRange: '€€',
    rating: 4.5,
    cover: '#FDF8F4',
    coverEmoji: '🪑',
    tags: ['Faubourg Montmartre', 'Bistrot', 'Naturel'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/leparisdalexis',
    description: 'Un bistrot naturel confidentiel rue Papillon, dans l\'énergie du Faubourg Montmartre. Cuisine simple et bien faite, jolis vins de petits vignerons et ambiance décontractée de quartier.',
    lat: 48.8773, lng: 2.3460,
  },
  {
    id: '92',
    name: 'Fellows',
    cuisine: 'Française',
    city: 'Paris',
    address: '84 Rue du Faubourg Saint-Denis, 75010',
    priceRange: '€€',
    rating: 4.6,
    cover: '#F5FBF7',
    coverEmoji: '🤝',
    tags: ['Faubourg Saint-Denis', 'Bistronomique', 'Trendy'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/leparisdalexis',
    description: 'L\'un des bistronomiques en vue du Faubourg Saint-Denis. Cuisine créative et accessible dans l\'un des couloirs les plus animés de Paris, avec une sélection de vins bien pensée.',
    lat: 48.8713, lng: 2.3555,
  },
]
