export interface Influencer {
  handle: string
  name: string
  followers: string
  avatar: string // emoji fallback
}

export interface Restaurant {
  id: string
  name: string
  cuisine: string
  city: string
  address: string
  priceRange: '€' | '€€' | '€€€' | '€€€€'
  rating: number
  cover: string
  coverEmoji: string
  tags: string[]
  recommendedBy: Influencer
  coRecommendedBy?: Influencer[]
  instagramPost: string
  description: string
  lat: number
  lng: number
}

export const CITIES = ['Toutes les villes', 'Paris', 'Lyon', 'Marseille', 'Bordeaux', 'Nice', 'Toulouse']
export const CUISINES = ['Toutes les cuisines', 'Française', 'Japonaise', 'Italienne', 'Coréenne', 'Mexicaine', 'Libanaise', 'Grecque', 'Péruvienne', 'Végétarienne', 'Américaine', 'Britannique', 'Vietnamienne', 'Thaïlandaise', 'Antillaise', 'Chinoise']

export const RESTAURANTS: Restaurant[] = [
  {
    id: '1',
    name: 'Kibo',
    cuisine: 'Japonaise',
    city: 'Paris',
    address: '18 rue du Faubourg Saint-Antoine, 75011',
    priceRange: '€€€',
    rating: 4.8,
    cover: '#FDF0FD',
    coverEmoji: '🍣',
    tags: ['Omakase', 'Incontournable', 'Réservation obligatoire'],
    recommendedBy: {
      handle: '@philoudarblay',
      name: 'Philou d\'Arblay',
      followers: '153K',
      avatar: '👩‍🍳',
    },
    instagramPost: 'https://www.instagram.com/philoudarblay',
    description: 'Un comptoir omakase confidentiel où le chef propose 12 services autour du meilleur poisson de saison. Liste d\'attente de plusieurs semaines.',
    lat: 48.8535,
    lng: 2.3714,
  },
  {
    id: '13',
    name: 'Club Cochon L\'Auberge',
    cuisine: 'Française',
    city: 'Paris',
    address: '4 rue Drouot, 75009',
    priceRange: '€€',
    rating: 4.6,
    cover: '#FFF8EC',
    coverEmoji: '🐷',
    tags: ['Bistrot', 'Canaille', 'Vin nature'],
    recommendedBy: {
      handle: '@philoudarblay',
      name: 'Philou d\'Arblay',
      followers: '153K',
      avatar: '👩‍🍳',
    },
    coRecommendedBy: [{ handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' }],
    instagramPost: 'https://www.instagram.com/p/DXMtCbmkXwI/',
    description: 'Le bistrot canaille de la rue Drouot, prolongement de l\'emblématique Club Cochon du Passage des Panoramas. Cuisine du cochon de la tête aux pieds, vins nature et ambiance de comptoir chaleureuse.',
    lat: 48.8757,
    lng: 2.3464,
  },
  {
    id: '14',
    name: 'L\'Auberge des Crus',
    cuisine: 'Française',
    city: 'Paris',
    address: '13 rue Bosio, 75016',
    priceRange: '€€€',
    rating: 4.7,
    cover: '#EBE9FA',
    coverEmoji: '🍾',
    tags: ['Terroir', 'Cave', 'Bistrot chic'],
    recommendedBy: {
      handle: '@philoudarblay',
      name: 'Philou d\'Arblay',
      followers: '153K',
      avatar: '👩‍🍳',
    },
    instagramPost: 'https://www.instagram.com/p/DXMtCbmkXwI/',
    description: 'Atmosphère de maison de campagne en plein Paris 16e. Boiseries, bar en bois des années 40 et cave à vins dédiée à la dégustation. Cuisine du terroir signée par le chef Charles Laborde.',
    lat: 48.8552,
    lng: 2.2706,
  },
  {
    id: '15',
    name: 'Spécimen Burger Saint-Germain',
    cuisine: 'Américaine',
    city: 'Paris',
    address: '3 Rue Guisarde, 75006',
    priceRange: '€€',
    rating: 4.5,
    cover: '#FFF8EC',
    coverEmoji: '🍔',
    tags: ['Burger', 'Saint-Germain', 'Fait maison'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/p/DXW_wgKiDMD/',
    description: 'Le burger gastronomique de Saint-Germain-des-Prés. Viande sélectionnée, buns maison et sauces signature dans un cadre soigné.',
    lat: 48.8524, lng: 2.3353,
  },
  {
    id: '16',
    name: 'Club Cochon',
    cuisine: 'Française',
    city: 'Paris',
    address: '38 Passage des Panoramas, 75002',
    priceRange: '€€',
    rating: 4.7,
    cover: '#FFF8EC',
    coverEmoji: '🐷',
    tags: ['Bistrot', 'Cochon', 'Passage couvert'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    coRecommendedBy: [{ handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' }],
    instagramPost: 'https://www.instagram.com/p/DXMtCbmkXwI/',
    description: 'L\'adresse historique du Club Cochon, nichée dans le mythique Passage des Panoramas. Fromage de tête, rillettes et cochon de lait rôti dans un décor de comptoir parisien.',
    lat: 48.8697, lng: 2.3453,
  },
  {
    id: '17',
    name: 'Chez Margaux',
    cuisine: 'Française',
    city: 'Paris',
    address: '10 Avenue de New York, 75116',
    priceRange: '€€€',
    rating: 4.6,
    cover: '#ECF8F6',
    coverEmoji: '🌿',
    tags: ['Vue Seine', 'Terrasse', 'Bistronomique'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/p/DXMtCbmkXwI/',
    description: 'Face à la Seine et au Trocadéro, Chez Margaux propose une cuisine française soignée avec l\'une des plus belles terrasses de Paris. Poissons du marché et viandes rôties.',
    lat: 48.8631, lng: 2.2936,
  },
  {
    id: '18',
    name: 'À La Renaissance',
    cuisine: 'Française',
    city: 'Paris',
    address: '87 Rue de la Roquette, 75011',
    priceRange: '€€',
    rating: 4.5,
    cover: '#EBE9FA',
    coverEmoji: '🍷',
    tags: ['Bistrot de quartier', 'Vin nature', 'Oberkampf'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/p/DXMtCbmkXwI/',
    description: 'Un bistrot authentique de la Roquette, resté dans son jus depuis des décennies. Cave à vins de caractère et plats du jour généreux à l\'ardoise.',
    lat: 48.8563, lng: 2.3756,
  },
  {
    id: '19',
    name: 'Bistrot Darsy',
    cuisine: 'Française',
    city: 'Paris',
    address: '15 Rue des Panoyaux, 75020',
    priceRange: '€€',
    rating: 4.5,
    cover: '#F5FBF7',
    coverEmoji: '🥩',
    tags: ['Ménilmontant', 'Bistrot', 'Local'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/p/DXMtCbmkXwI/',
    description: 'Caché dans une rue discrète de Ménilmontant, Bistrot Darsy régale les habitués avec une cuisine de marché sans chichis et une atmosphère de vrai bistrot parisien populaire.',
    lat: 48.8648, lng: 2.3922,
  },
  {
    id: '20',
    name: 'Paul Chêne Cherche-Midi',
    cuisine: 'Française',
    city: 'Paris',
    address: '79 Rue du Cherche-Midi, 75006',
    priceRange: '€€€',
    rating: 4.7,
    cover: '#FDF0FD',
    coverEmoji: '🫕',
    tags: ['Gastronomique', 'Saint-Germain', 'Chef étoilé'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/p/DXMtCbmkXwI/',
    description: 'La table de Charles Laborde dans le 6e, une cuisine française précise et généreuse. Produits nobles travaillés avec finesse, carte courte qui change selon les saisons.',
    lat: 48.8479, lng: 2.3296,
  },
  {
    id: '21',
    name: 'Maison Baroche',
    cuisine: 'Française',
    city: 'Paris',
    address: '18 Rue Cadet, 75009',
    priceRange: '€€',
    rating: 4.6,
    cover: '#FDF8F4',
    coverEmoji: '🍽️',
    tags: ['Faubourg Montmartre', 'Bistronomique', 'Ardoise'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/p/DVQ5QngCAkD/?img_index=1',
    description: 'Une maison chaleureuse rue Cadet, entre Opéra et Montmartre. Cuisine bistronomique à l\'ardoise, produits sourcés avec soin et accueil aux petits oignons.',
    lat: 48.8757, lng: 2.3441,
  },
  {
    id: '22',
    name: 'Bon Vivant',
    cuisine: 'Française',
    city: 'Paris',
    address: '7 Rue des Écoles, 75005',
    priceRange: '€€',
    rating: 4.5,
    cover: '#ECF8F6',
    coverEmoji: '🥗',
    tags: ['Latin', 'Déjeuner', 'Terrasse'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/philoudarblay',
    description: 'En plein Quartier Latin, Bon Vivant incarne la brasserie de quartier idéale. Plats bistrotiers, belle cave et une terrasse agréable face à la vie du 5e.',
    lat: 48.8499, lng: 2.3522,
  },
  {
    id: '23',
    name: 'Chez Marcel',
    cuisine: 'Française',
    city: 'Paris',
    address: '7 Rue Stanislas, 75006',
    priceRange: '€€',
    rating: 4.6,
    cover: '#FFF8EC',
    coverEmoji: '🥘',
    tags: ['Bistrot classique', 'Lyonnais', 'Saint-Germain'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/p/DVjLClICFp2/',
    description: 'Un authentique bistrot lyonnais à Paris, repris par une famille passionnée. Tablier de sapeur, quenelles et pot de Beaujolais dans un décor rétro immuable.',
    lat: 48.8434, lng: 2.3325,
  },
  {
    id: '24',
    name: 'Épopée',
    cuisine: 'Française',
    city: 'Paris',
    address: '52 Rue Léon Frot, 75011',
    priceRange: '€€',
    rating: 4.7,
    cover: '#EBE9FA',
    coverEmoji: '✨',
    tags: ['Charonne', 'Néobistrot', 'Créatif'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/p/DU8uo40CL2v/',
    description: 'L\'un des néobistrots phares du 11e. Cuisine inventive et généreuse, service décontracté et carte des vins nature soigneusement sélectionnée.',
    lat: 48.8567, lng: 2.3845,
  },
  {
    id: '25',
    name: 'Castille Paris',
    cuisine: 'Française',
    city: 'Paris',
    address: '33-37 Rue Cambon, 75001',
    priceRange: '€€€€',
    rating: 4.8,
    cover: '#FDF0FD',
    coverEmoji: '🏛️',
    tags: ['Palace', 'Luxe', 'Vendôme'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/philoudarblay',
    description: 'Le restaurant gastronomique de l\'hôtel Castille, à deux pas de la Place Vendôme. Cuisine française d\'exception dans un cadre élégant aux accents italiens.',
    lat: 48.8659, lng: 2.3266,
  },
  {
    id: '26',
    name: 'Restaurant Anne',
    cuisine: 'Française',
    city: 'Paris',
    address: '28 Place des Vosges, 75003',
    priceRange: '€€€',
    rating: 4.8,
    cover: '#ECF8F6',
    coverEmoji: '🏰',
    tags: ['Place des Vosges', 'Arcades', 'Gastronomique'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/philoudarblay',
    description: 'Sous les arcades de la plus belle place de Paris, Restaurant Anne propose une cuisine française raffinée dans un cadre historique inégalable. Vue imprenable sur la Place des Vosges.',
    lat: 48.8557, lng: 2.3623,
  },
  {
    id: '27',
    name: 'Eme Restaurant',
    cuisine: 'Française',
    city: 'Paris',
    address: '4 Impasse Guéménée, 75004',
    priceRange: '€€€',
    rating: 4.7,
    cover: '#FDF8F4',
    coverEmoji: '🌀',
    tags: ['Caché', 'Marais', 'Confidentiel'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/p/DU8uo40CL2v/',
    description: 'Planqué dans une impasse du Marais, ce restaurant confidentiel réserve de belles surprises. Menu unique autour de produits d\'exception, cuisine ouverte sur la salle.',
    lat: 48.8536, lng: 2.3675,
  },
  {
    id: '28',
    name: 'Cypsele',
    cuisine: 'Grecque',
    city: 'Paris',
    address: '11 Rue des Deux Ponts, 75004',
    priceRange: '€€',
    rating: 4.6,
    cover: '#ECF8F6',
    coverEmoji: '🫒',
    tags: ['Île Saint-Louis', 'Grec contemporain', 'Mezze'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/p/DU8uo40CL2v/',
    description: 'Une table grecque moderne sur l\'Île Saint-Louis. Mezze raffinés, poissons grillés et vins grecs naturels dans un décor épuré. Une adresse confidentielle très courue.',
    lat: 48.8520, lng: 2.3554,
  },
  {
    id: '29',
    name: 'Rôtisserie Segar',
    cuisine: 'Française',
    city: 'Paris',
    address: '111 Rue Mouffetard, 75005',
    priceRange: '€€',
    rating: 4.6,
    cover: '#FFF8EC',
    coverEmoji: '🍗',
    tags: ['Rôtisserie', 'Mouffetard', 'Volaille'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/philoudarblay',
    description: 'La rôtisserie de référence de la Rue Mouffetard. Poulets et pintades rôtis à la broche, pommes de terre fondantes et jus de cuisson doré. Simple, parfait.',
    lat: 48.8420, lng: 2.3509,
  },
  {
    id: '30',
    name: 'Le Petit Vendôme',
    cuisine: 'Française',
    city: 'Paris',
    address: '8 Rue des Capucines, 75002',
    priceRange: '€€',
    rating: 4.5,
    cover: '#F5FBF7',
    coverEmoji: '🥪',
    tags: ['Sandwich', 'Opéra', 'Bistrot'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/philoudarblay',
    description: 'Une institution du quartier Opéra, célèbre pour ses sandwichs maison et sa carte de bistrot immuable. Zinc, miroirs et habitués fidèles depuis des générations.',
    lat: 48.8697, lng: 2.3308,
  },
  {
    id: '31',
    name: 'Chez Georges',
    cuisine: 'Française',
    city: 'Paris',
    address: '1 Rue du Mail, 75002',
    priceRange: '€€€',
    rating: 4.8,
    cover: '#EBE9FA',
    coverEmoji: '🪄',
    tags: ['Institution', 'Classique', 'Bourse'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/p/DTsv_gpDP_F/',
    description: 'L\'une des grandes tables de bistrot parisien, ouverte depuis 1964. Steak tartare, sole meunière et crème caramel dans un décor à l\'ancienne d\'une authenticité rare.',
    lat: 48.8660, lng: 2.3469,
  },
  {
    id: '32',
    name: 'LAZU — Bouillon 47',
    cuisine: 'Française',
    city: 'Paris',
    address: '47 Rue Marguerite de Rochechouart, 75009',
    priceRange: '€',
    rating: 4.5,
    cover: '#FDF0FD',
    coverEmoji: '🫙',
    tags: ['Bouillon', 'Pigalle', 'Accessible'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/philoudarblay',
    description: 'Le bouillon populaire de Pigalle signé LAZU. Cuisine française traditionnelle à prix doux, œufs mayo, bœuf bourguignon et profiteroles dans une grande salle animée.',
    lat: 48.8798, lng: 2.3426,
  },
  {
    id: '33',
    name: 'Le Comptoir LAZU',
    cuisine: 'Française',
    city: 'Paris',
    address: '36 Rue Marguerite de Rochechouart, 75009',
    priceRange: '€',
    rating: 4.4,
    cover: '#FDF0FD',
    coverEmoji: '☕',
    tags: ['Comptoir', 'Pigalle', 'Déjeuner'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/philoudarblay',
    description: 'Le petit frère du Bouillon 47, en version comptoir et déjeuner rapide. Plat du jour, verre de vin et dessert maison — le ticket moyen le plus honnête du quartier.',
    lat: 48.8797, lng: 2.3420,
  },
  {
    id: '34',
    name: 'Le Mâche-Dru',
    cuisine: 'Française',
    city: 'Paris',
    address: '60 Rue Saint-Louis-en-l\'Île, 75004',
    priceRange: '€€',
    rating: 4.6,
    cover: '#F5FBF7',
    coverEmoji: '🏝️',
    tags: ['Île Saint-Louis', 'Bistrot', 'Marché'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/philoudarblay',
    description: 'Sur la rue principale de l\'Île Saint-Louis, ce bistrot attachant propose une cuisine de marché honnête loin du piège à touristes. Ambiance de village en plein Paris.',
    lat: 48.8514, lng: 2.3568,
  },
  {
    id: '35',
    name: 'L\'Entente — British Brasserie',
    cuisine: 'Britannique',
    city: 'Paris',
    address: '13 Rue Monsigny, 75002',
    priceRange: '€€',
    rating: 4.5,
    cover: '#ECF8F6',
    coverEmoji: '🫖',
    tags: ['British', 'Brunch', 'Opéra'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/philoudarblay',
    description: 'La cordiale entente franco-britannique dans l\'assiette. Fish & chips de poisson noble, Sunday roast et gin-tonics soignés dans un décor londonien assumé en plein Paris.',
    lat: 48.8700, lng: 2.3408,
  },
  {
    id: '36',
    name: 'La Maison de la Pistache',
    cuisine: 'Libanaise',
    city: 'Paris',
    address: '65 Rue du Bac, 75007',
    priceRange: '€',
    rating: 4.7,
    cover: '#F5FBF7',
    coverEmoji: '🟢',
    tags: ['Pistache', 'Libanais', 'Pâtisserie'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/philoudarblay',
    description: 'Le temple parisien de la pistache libanaise. Knafeh à la pistache, baklawa et croissant pistache-rose qui a fait le tour d\'Instagram. File d\'attente assurée le week-end.',
    lat: 48.8554, lng: 2.3250,
  },
  {
    id: '37',
    name: 'Arcane 17',
    cuisine: 'Française',
    city: 'Paris',
    address: '17 Rue Charlot, 75003',
    priceRange: '€€',
    rating: 4.6,
    cover: '#EBE9FA',
    coverEmoji: '🃏',
    tags: ['Haut Marais', 'Néobistrot', 'Naturel'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/philoudarblay',
    description: 'Une adresse à l\'image du Haut Marais : branchée, soignée et sans esbroufe. Cuisine de saison créative, belle liste de vins nature et salle lumineuse très cosy.',
    lat: 48.8625, lng: 2.3596,
  },
  {
    id: '38',
    name: 'Vivide',
    cuisine: 'Française',
    city: 'Paris',
    address: '3 Rue Dancourt, 75018',
    priceRange: '€€€',
    rating: 4.8,
    cover: '#FDF0FD',
    coverEmoji: '🎨',
    tags: ['Montmartre', 'Gastronomique', 'Créatif'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/philoudarblay',
    description: 'À deux pas du Moulin Rouge, Vivide propose une cuisine gastronomique française d\'une rare créativité. Menu dégustation en constante évolution, produits d\'exception et service attentionné.',
    lat: 48.8841, lng: 2.3488,
  },
  {
    id: '39',
    name: 'Quedubon',
    cuisine: 'Française',
    city: 'Paris',
    address: '22 Rue du Plateau, 75019',
    priceRange: '€€',
    rating: 4.7,
    cover: '#F5FBF7',
    coverEmoji: '🍾',
    tags: ['Buttes-Chaumont', 'Cave à manger', 'Nature'],
    recommendedBy: { handle: '@theovoyageurgourmand', name: 'Théo, Voyageur Gourmand', followers: '185K', avatar: '🧑‍🍳' },
    instagramPost: 'https://www.instagram.com/theovoyageurgourmand',
    description: 'La cave à manger de référence des Buttes-Chaumont. Sélection pointue de vins naturels, assiettes généreuses de charcuterie et fromages affinés dans un quartier devenu très couru.',
    lat: 48.8814, lng: 2.3727,
  },
  {
    id: '40',
    name: 'Le Baratin',
    cuisine: 'Française',
    city: 'Paris',
    address: '3 Rue Jouye-Rouve, 75020',
    priceRange: '€€',
    rating: 4.8,
    cover: '#EBE9FA',
    coverEmoji: '🍷',
    tags: ['Belleville', 'Vin nature', 'Bistrot culte'],
    recommendedBy: { handle: '@theovoyageurgourmand', name: 'Théo, Voyageur Gourmand', followers: '185K', avatar: '🧑‍🍳' },
    instagramPost: 'https://www.instagram.com/theovoyageurgourmand',
    description: 'Une institution du vin nature à Belleville. Raquel Carena tient cette cave à manger depuis des décennies, réputée pour sa sélection pointue et sa cuisine franche du collier.',
    lat: 48.8726, lng: 2.3903,
  },
  {
    id: '41',
    name: 'Patine',
    cuisine: 'Française',
    city: 'Paris',
    address: '16 Rue la Vacquerie, 75011',
    priceRange: '€€€',
    rating: 4.7,
    cover: '#FDF8F4',
    coverEmoji: '🕯️',
    tags: ['Bistronomique', 'Oberkampf', 'Créatif'],
    recommendedBy: { handle: '@theovoyageurgourmand', name: 'Théo, Voyageur Gourmand', followers: '185K', avatar: '🧑‍🍳' },
    instagramPost: 'https://www.instagram.com/theovoyageurgourmand',
    description: 'Une adresse discrète du 11e qui mise sur une cuisine fine et créative. Carte courte, produits travaillés avec soin, atmosphère intime et chaleureuse.',
    lat: 48.8553, lng: 2.3810,
  },
  {
    id: '42',
    name: 'Gramme',
    cuisine: 'Française',
    city: 'Paris',
    address: '96 Rue Jean-Pierre Timbaud, 75011',
    priceRange: '€',
    rating: 4.5,
    cover: '#F5FBF7',
    coverEmoji: '☕',
    tags: ['Café', 'Brunch', 'Timbaud'],
    recommendedBy: { handle: '@theovoyageurgourmand', name: 'Théo, Voyageur Gourmand', followers: '185K', avatar: '🧑‍🍳' },
    instagramPost: 'https://www.instagram.com/p/DT8Q734CBm7/',
    description: 'Le café de quartier idéal de la rue Timbaud. Brunch soigné, viennoiseries maison et carte simple mais impeccable dans un espace lumineux très Oberkampf.',
    lat: 48.8657, lng: 2.3762,
  },
  {
    id: '43',
    name: 'Erso',
    cuisine: 'Française',
    city: 'Paris',
    address: '18 Rue Saint-Ambroise, 75011',
    priceRange: '€€',
    rating: 4.6,
    cover: '#ECF8F6',
    coverEmoji: '🌾',
    tags: ['Naturel', '11e', 'Ardoise'],
    recommendedBy: { handle: '@theovoyageurgourmand', name: 'Théo, Voyageur Gourmand', followers: '185K', avatar: '🧑‍🍳' },
    instagramPost: 'https://www.instagram.com/theovoyageurgourmand',
    description: 'Un bistrot naturel ancré dans le 11e, fidèle aux producteurs locaux et aux vins sans soufre. Menu du marché à l\'ardoise, ambiance décontractée et généreuse.',
    lat: 48.8624, lng: 2.3769,
  },
  {
    id: '44',
    name: 'Slak Paris',
    cuisine: 'Française',
    city: 'Paris',
    address: '27 Rue Pierre Fontaine, 75009',
    priceRange: '€€',
    rating: 4.5,
    cover: '#FDF0FD',
    coverEmoji: '🎵',
    tags: ['Pigalle', 'Cocktails', 'Festif'],
    recommendedBy: { handle: '@theovoyageurgourmand', name: 'Théo, Voyageur Gourmand', followers: '185K', avatar: '🧑‍🍳' },
    instagramPost: 'https://www.instagram.com/theovoyageurgourmand',
    description: 'En plein Pigalle, Slak conjugue bonne cuisine et ambiance musicale. Plats généreux à partager, cocktails créatifs et salle qui monte en puissance en soirée.',
    lat: 48.8824, lng: 2.3347,
  },
  {
    id: '45',
    name: 'Lacigne',
    cuisine: 'Française',
    city: 'Paris',
    address: '124 Avenue Parmentier, 75011',
    priceRange: '€€',
    rating: 4.6,
    cover: '#FFF8EC',
    coverEmoji: '🦢',
    tags: ['Parmentier', 'Bistronomique', 'Cave'],
    recommendedBy: { handle: '@theovoyageurgourmand', name: 'Théo, Voyageur Gourmand', followers: '185K', avatar: '🧑‍🍳' },
    instagramPost: 'https://www.instagram.com/theovoyageurgourmand',
    description: 'Une table soignée avenue Parmentier, entre bistrot et cave à manger. Cuisine française précise, belle sélection de vins naturels et service attentionné.',
    lat: 48.8641, lng: 2.3795,
  },
  {
    id: '46',
    name: 'Dents de Loup',
    cuisine: 'Française',
    city: 'Paris',
    address: '75 Rue Marguerite de Rochechouart, 75009',
    priceRange: '€€',
    rating: 4.6,
    cover: '#EBE9FA',
    coverEmoji: '🐺',
    tags: ['Pigalle', 'Bistrot', 'Vin nature'],
    recommendedBy: { handle: '@theovoyageurgourmand', name: 'Théo, Voyageur Gourmand', followers: '185K', avatar: '🧑‍🍳' },
    instagramPost: 'https://www.instagram.com/theovoyageurgourmand',
    description: 'Bistrot nature à deux pas de Pigalle. Petite carte qui change selon les arrivages, vins vivants et atmosphère de cave chaleureuse très appréciée des habitués.',
    lat: 48.8822, lng: 2.3466,
  },
  {
    id: '47',
    name: 'Pastasuta',
    cuisine: 'Italienne',
    city: 'Paris',
    address: '9 Rue du Faubourg Poissonnière, 75009',
    priceRange: '€',
    rating: 4.7,
    cover: '#FDF8F4',
    coverEmoji: '🍝',
    tags: ['Pasta fraîche', 'Faubourg', 'Rapide'],
    recommendedBy: { handle: '@theovoyageurgourmand', name: 'Théo, Voyageur Gourmand', followers: '185K', avatar: '🧑‍🍳' },
    instagramPost: 'https://www.instagram.com/theovoyageurgourmand',
    description: 'Pâtes fraîches préparées sous vos yeux, sauces généreuses et prix doux. Le spot parfait pour un déjeuner rapide et authentique à deux pas des Grands Boulevards.',
    lat: 48.8736, lng: 2.3493,
  },
  {
    id: '48',
    name: 'Tuan',
    cuisine: 'Vietnamienne',
    city: 'Paris',
    address: '24 Rue de Babylone, 75007',
    priceRange: '€€',
    rating: 4.7,
    cover: '#F5FBF7',
    coverEmoji: '🍜',
    tags: ['Vietnamien', 'Saint-Germain', 'Gastronomique'],
    recommendedBy: { handle: '@theovoyageurgourmand', name: 'Théo, Voyageur Gourmand', followers: '185K', avatar: '🧑‍🍳' },
    instagramPost: 'https://www.instagram.com/theovoyageurgourmand',
    description: 'La cuisine vietnamienne gastronomique du 7e. Pho de bœuf longuement mijoté, rouleaux de printemps maison et bo bun parfumé dans un cadre élégant et feutré.',
    lat: 48.8524, lng: 2.3214,
  },
  {
    id: '49',
    name: 'Irwin',
    cuisine: 'Française',
    city: 'Paris',
    address: '22 Rue Cambacérès, 75008',
    priceRange: '€€€',
    rating: 4.7,
    cover: '#ECF8F6',
    coverEmoji: '🌿',
    tags: ['8e', 'Gastronomique', 'Élégant'],
    recommendedBy: { handle: '@theovoyageurgourmand', name: 'Théo, Voyageur Gourmand', followers: '185K', avatar: '🧑‍🍳' },
    instagramPost: 'https://www.instagram.com/theovoyageurgourmand',
    description: 'Une table gastronomique discrète dans le 8e. Cuisine française contemporaine, produits d\'exception et service impeccable dans un décor sobre et raffiné.',
    lat: 48.8745, lng: 2.3152,
  },
  {
    id: '50',
    name: 'Alliance',
    cuisine: 'Française',
    city: 'Paris',
    address: '5 Rue de Poissy, 75005',
    priceRange: '€€€€',
    rating: 4.9,
    cover: '#FDF0FD',
    coverEmoji: '⭐',
    tags: ['Étoilé', 'Gastronomique', 'Latin'],
    recommendedBy: { handle: '@theovoyageurgourmand', name: 'Théo, Voyageur Gourmand', followers: '185K', avatar: '🧑‍🍳' },
    instagramPost: 'https://www.instagram.com/theovoyageurgourmand',
    description: 'Table étoilée du Quartier Latin, tenue par Thibaut Spiwack. Cuisine végétale et durable d\'une finesse remarquable, engagée dans une démarche environnementale exemplaire.',
    lat: 48.8507, lng: 2.3529,
  },
  {
    id: '51',
    name: 'Le Pigeon de Dandelion',
    cuisine: 'Française',
    city: 'Paris',
    address: '46 Rue des Vignoles, 75020',
    priceRange: '€€',
    rating: 4.6,
    cover: '#FDF8F4',
    coverEmoji: '🕊️',
    tags: ['Charonne', 'Créatif', 'Confidentiel'],
    recommendedBy: { handle: '@theovoyageurgourmand', name: 'Théo, Voyageur Gourmand', followers: '185K', avatar: '🧑‍🍳' },
    instagramPost: 'https://www.instagram.com/theovoyageurgourmand',
    description: 'Planqué dans la rue des Vignoles, ce bistrot créatif mise sur des associations inattendues et des produits sourcés avec soin. Une adresse confidentielle qui mérite le détour.',
    lat: 48.8590, lng: 2.3990,
  },
  {
    id: '52',
    name: 'Paul Bert',
    cuisine: 'Française',
    city: 'Paris',
    address: '18 Rue Paul Bert, 75011',
    priceRange: '€€€',
    rating: 4.8,
    cover: '#EBE9FA',
    coverEmoji: '🥩',
    tags: ['Bistrot classique', 'Faubourg Saint-Antoine', 'Institution'],
    recommendedBy: { handle: '@theovoyageurgourmand', name: 'Théo, Voyageur Gourmand', followers: '185K', avatar: '🧑‍🍳' },
    instagramPost: 'https://www.instagram.com/theovoyageurgourmand',
    description: 'L\'un des grands bistrots parisiens, véritable institution du Faubourg Saint-Antoine. Entrecôte Café de Paris, tarte tatin et cave à vins de collection dans un décor immuable.',
    lat: 48.8524, lng: 2.3868,
  },
  {
    id: '53',
    name: 'Tsukizi',
    cuisine: 'Japonaise',
    city: 'Paris',
    address: '2 Bis Rue des Ciseaux, 75006',
    priceRange: '€€',
    rating: 4.7,
    cover: '#FDF0FD',
    coverEmoji: '🍱',
    tags: ['Sushi', 'Saint-Germain', 'Authentique'],
    recommendedBy: { handle: '@theovoyageurgourmand', name: 'Théo, Voyageur Gourmand', followers: '185K', avatar: '🧑‍🍳' },
    instagramPost: 'https://www.instagram.com/theovoyageurgourmand',
    description: 'Petit comptoir japonais confidentiel à Saint-Germain. Sushis et sashimis d\'une fraîcheur irréprochable, préparés devant vous par un chef formé au Japon. Réservation vivement conseillée.',
    lat: 48.8532, lng: 2.3364,
  },
  {
    id: '54',
    name: 'Tara Café Vin',
    cuisine: 'Française',
    city: 'Paris',
    address: '2 Rue de la Fontaine au Roi, 75011',
    priceRange: '€€',
    rating: 4.6,
    cover: '#F5FBF7',
    coverEmoji: '🫗',
    tags: ['Cave à manger', 'Fontaine au Roi', 'Nature'],
    recommendedBy: { handle: '@theovoyageurgourmand', name: 'Théo, Voyageur Gourmand', followers: '185K', avatar: '🧑‍🍳' },
    instagramPost: 'https://www.instagram.com/theovoyageurgourmand',
    description: 'Cave à manger chaleureuse à l\'entrée du 11e. Vins naturels de petits vignerons, assiettes à partager généreuses et ambiance de comptoir qui donne envie de s\'attarder.',
    lat: 48.8670, lng: 2.3638,
  },
  {
    id: '55',
    name: 'Maison Rostang',
    cuisine: 'Française',
    city: 'Paris',
    address: '20 Rue Rennequin, 75017',
    priceRange: '€€€€',
    rating: 4.9,
    cover: '#FDF0FD',
    coverEmoji: '⭐',
    tags: ['2 étoiles Michelin', 'Gastronomique', 'Ternes'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/p/DLFmPB8iWKZ/',
    description: 'La grande maison de Michel Rostang, deux étoiles Michelin depuis des décennies. Cuisine française d\'exception, service impeccable et cadre bourgeois raffiné dans le 17e.',
    lat: 48.8806, lng: 2.2996,
  },
  {
    id: '56',
    name: 'Biche Paris',
    cuisine: 'Française',
    city: 'Paris',
    address: '129 Rue du Faubourg Saint-Honoré, 75008',
    priceRange: '€€€',
    rating: 4.7,
    cover: '#ECF8F6',
    coverEmoji: '🦌',
    tags: ['Faubourg Saint-Honoré', 'Chic', 'Bistronomique'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/p/DCv8feguAqc/',
    description: 'Une adresse élégante du Faubourg Saint-Honoré, entre brasserie chic et bistrot gastronomique. Cuisine française soignée dans un décor lumineux très apprécié des habitués du quartier.',
    lat: 48.8739, lng: 2.3075,
  },
  {
    id: '57',
    name: 'Ô\'Cocher',
    cuisine: 'Française',
    city: 'Paris',
    address: '45 Rue de Babylone, 75007',
    priceRange: '€€',
    rating: 4.6,
    cover: '#FFF8EC',
    coverEmoji: '🐎',
    tags: ['7e', 'Bistrot', 'Quartier'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/leparisdalexis',
    description: 'Le bistrot de quartier du 7e qui régale les riverains comme les touristes égarés. Cuisine française simple et généreuse, carte courte bien ficelée et service souriant.',
    lat: 48.8516, lng: 2.3210,
  },
  {
    id: '58',
    name: 'Braise',
    cuisine: 'Française',
    city: 'Paris',
    address: '19 Rue d\'Anjou, 75008',
    priceRange: '€€€',
    rating: 4.7,
    cover: '#FFF8EC',
    coverEmoji: '🔥',
    tags: ['Grill', 'Viande', 'Madeleine'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/p/DVRKThziHZP/',
    description: 'La table du feu de bois dans le 8e. Viandes et légumes cuits à la braise, fumés avec précision par un chef maîtrisant la cuisson au charbon de bois comme peu savent le faire à Paris.',
    lat: 48.8752, lng: 2.3237,
  },
  {
    id: '59',
    name: 'Vida\'M',
    cuisine: 'Française',
    city: 'Paris',
    address: '34 Rue de Cambrai, 75019',
    priceRange: '€€',
    rating: 4.5,
    cover: '#F5FBF7',
    coverEmoji: '🌈',
    tags: ['19e', 'Fusion', 'Contemporain'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/leparisdalexis',
    description: 'Une adresse dynamique du 19e qui mêle influences françaises et internationales. Cuisine créative aux influences multiples, cadre convivial et carte de vins accessible.',
    lat: 48.8924, lng: 2.3687,
  },
  {
    id: '60',
    name: 'Pocha',
    cuisine: 'Coréenne',
    city: 'Paris',
    address: '82 Boulevard du Montparnasse, 75014',
    priceRange: '€€',
    rating: 4.6,
    cover: '#FDF8F4',
    coverEmoji: '🍶',
    tags: ['Pocha', 'Coréen', 'Montparnasse'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/p/DXPQscfiKon/',
    description: 'L\'esprit des bars à snacks coréens au pied du Montparnasse. Pancakes coréens, poulet frit épicé et soju en pichet dans une ambiance festive et décontractée.',
    lat: 48.8431, lng: 2.3262,
  },
  {
    id: '61',
    name: 'Pocha',
    cuisine: 'Coréenne',
    city: 'Paris',
    address: '21 Rue Saint-Augustin, 75002',
    priceRange: '€€',
    rating: 4.6,
    cover: '#FDF8F4',
    coverEmoji: '🍶',
    tags: ['Pocha', 'Coréen', 'Opéra'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/p/DXPQscfiKon/',
    description: 'La deuxième adresse Pocha, côté Opéra. Même ambiance pocha, mêmes classiques coréens à partager — tteokbokki, pajeon et makgeolli — dans un quartier plus central.',
    lat: 48.8694, lng: 2.3359,
  },
  {
    id: '62',
    name: 'Rotisserie Cotcotgardette',
    cuisine: 'Française',
    city: 'Paris',
    address: '22 Rue Rochebrune, 75011',
    priceRange: '€€',
    rating: 4.6,
    cover: '#FFF8EC',
    coverEmoji: '🍗',
    tags: ['Rôtisserie', 'Voltaire', 'Volaille'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/leparisdalexis',
    description: 'La rôtisserie du quartier Voltaire. Poulets fermiers et légumes rôtis à la broche, jus de cuisson doré servi en saucière. Simple, honnête et délicieux.',
    lat: 48.8552, lng: 2.3793,
  },
  {
    id: '63',
    name: 'Pâtisserie Adroyte',
    cuisine: 'Française',
    city: 'Paris',
    address: '14 Rue Froissart, 75003',
    priceRange: '€',
    rating: 4.7,
    cover: '#FDF0FD',
    coverEmoji: '🧁',
    tags: ['Pâtisserie', 'Marais', 'Créatif'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/leparisdalexis',
    description: 'La pâtisserie créative du Haut Marais. Tartes, entremets et viennoiseries à l\'esthétique soignée qui font le tour d\'Instagram avant d\'être dévorés avec délectation.',
    lat: 48.8613, lng: 2.3616,
  },
  {
    id: '64',
    name: 'BOULOM',
    cuisine: 'Française',
    city: 'Paris',
    address: '181 Rue Ordener, 75018',
    priceRange: '€',
    rating: 4.7,
    cover: '#F5FBF7',
    coverEmoji: '🥐',
    tags: ['Boulangerie', 'Montmartre', 'Artisanal'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/p/DXHhwazCFX-/',
    description: 'La boulangerie de référence du bas Montmartre. Pain au levain, croissants feuilletés et sandwichs généreux — une adresse de quartier qui a su devenir une institution.',
    lat: 48.8931, lng: 2.3461,
  },
  {
    id: '65',
    name: 'Libeyrouth',
    cuisine: 'Libanaise',
    city: 'Paris',
    address: '72 Rue Mouffetard, 75005',
    priceRange: '€€',
    rating: 4.7,
    cover: '#FDF8F4',
    coverEmoji: '🧆',
    tags: ['Libanais', 'Mouffetard', 'Mezze'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/p/DXHhwazCFX-/',
    description: 'L\'adresse libanaise incontournable de la Rue Mouffetard. Houmous maison, kibbeh et falafels croustillants — une cuisine familiale authentique dans un décor chaleureux.',
    lat: 48.8440, lng: 2.3502,
  },
  {
    id: '66',
    name: 'Kasumi',
    cuisine: 'Japonaise',
    city: 'Paris',
    address: '47 Rue de Richelieu, 75001',
    priceRange: '€€€',
    rating: 4.8,
    cover: '#ECF8F6',
    coverEmoji: '🍱',
    tags: ['Japonais', 'Palais-Royal', 'Kaiseki'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/leparisdalexis',
    description: 'Cuisine japonaise raffinée à deux pas du Palais-Royal. Menu dégustation inspiré du kaiseki, produits franco-japonais d\'exception et atmosphère zen pour une expérience hors du commun.',
    lat: 48.8648, lng: 2.3378,
  },
  {
    id: '67',
    name: 'Navigli Aperitivo',
    cuisine: 'Italienne',
    city: 'Paris',
    address: '52 Rue d\'Enghien, 75010',
    priceRange: '€€',
    rating: 4.5,
    cover: '#FDF0FD',
    coverEmoji: '🍹',
    tags: ['Aperitivo', 'Milan', 'Cocktails'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/leparisdalexis',
    description: 'L\'esprit des Navigli milanais transposé à Paris. Spritz, Negroni et buffet d\'aperitivo généreux à l\'heure de l\'apéro — une parenthèse italienne dans le 10e.',
    lat: 48.8737, lng: 2.3520,
  },
  {
    id: '68',
    name: 'Doma Paris',
    cuisine: 'Coréenne',
    city: 'Paris',
    address: '11 Rue Godot de Mauroy, 75009',
    priceRange: '€€',
    rating: 4.6,
    cover: '#EBE9FA',
    coverEmoji: '🥢',
    tags: ['Coréen', 'Opéra', 'Moderne'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/p/DXE892fCA-q/',
    description: 'Cuisine coréenne contemporaine dans le 9e. Bibimbap signature, japchae maison et makgeolli en cruche dans un décor épuré qui fait la part belle aux produits frais.',
    lat: 48.8748, lng: 2.3351,
  },
  {
    id: '69',
    name: 'Pastasuta',
    cuisine: 'Italienne',
    city: 'Paris',
    address: '2 Rue de la Coutellerie, 75004',
    priceRange: '€',
    rating: 4.7,
    cover: '#FDF8F4',
    coverEmoji: '🍝',
    tags: ['Pasta fraîche', 'Hôtel de Ville', 'Rapide'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/leparisdalexis',
    description: 'Pâtes fraîches roulées sous vos yeux près de l\'Hôtel de Ville. Carbonara, cacio e pepe et pesto maison — la recette du succès tient en trois ingrédients et beaucoup de savoir-faire.',
    lat: 48.8567, lng: 2.3493,
  },
  {
    id: '70',
    name: 'Kushikatsubon Paris',
    cuisine: 'Japonaise',
    city: 'Paris',
    address: '24 Rue Jean-Pierre Timbaud, 75011',
    priceRange: '€€',
    rating: 4.6,
    cover: '#FFF8EC',
    coverEmoji: '🍡',
    tags: ['Kushikatsu', 'Timbaud', 'Friture japonaise'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/leparisdalexis',
    description: 'Le seul restaurant spécialisé en kushikatsu de Paris — brochettes panées et frites originaires d\'Osaka. Viandes, légumes et fruits de mer en croûte légère, sauce maison interdite de double trempage.',
    lat: 48.8634, lng: 2.3742,
  },
  {
    id: '71',
    name: 'Black Angus',
    cuisine: 'Américaine',
    city: 'Paris',
    address: '8 Place de la République, 75011',
    priceRange: '€€€',
    rating: 4.6,
    cover: '#EBE9FA',
    coverEmoji: '🥩',
    tags: ['Steakhouse', 'République', 'Black Angus'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/leparisdalexis',
    description: 'Le steakhouse américain de référence place de la République. Bœuf Black Angus maturé, cuisson à la braise au charbon de bois et sauces maison pour les amateurs de viande exigeants.',
    lat: 48.8676, lng: 2.3635,
  },
  {
    id: '72',
    name: 'Black Angus',
    cuisine: 'Américaine',
    city: 'Paris',
    address: '96 Rue Saint-Lazare, 75009',
    priceRange: '€€€',
    rating: 4.6,
    cover: '#EBE9FA',
    coverEmoji: '🥩',
    tags: ['Steakhouse', 'Saint-Lazare', 'Black Angus'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/leparisdalexis',
    description: 'La deuxième adresse Black Angus côté Saint-Lazare. Même engagement sur la qualité de la viande et les cuissons maîtrisées, idéalement situé pour un dîner après le bureau.',
    lat: 48.8780, lng: 2.3329,
  },
  {
    id: '73',
    name: 'Khunakorn',
    cuisine: 'Thaïlandaise',
    city: 'Paris',
    address: '8 Avenue de Taillebourg, 75011',
    priceRange: '€€',
    rating: 4.7,
    cover: '#F5FBF7',
    coverEmoji: '🌶️',
    tags: ['Thaï', 'Nation', 'Authentique'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/leparisdalexis',
    description: 'La table thaïlandaise la plus authentique du 11e. Curry massaman, pad thaï à la crevette et som tam préparés par une équipe thaïe qui ne fait aucune concession sur les épices.',
    lat: 48.8535, lng: 2.3883,
  },
  {
    id: '74',
    name: 'Bomaye Club',
    cuisine: 'Française',
    city: 'Paris',
    address: '16 Rue de Paradis, 75010',
    priceRange: '€€',
    rating: 4.5,
    cover: '#FDF0FD',
    coverEmoji: '🎤',
    tags: ['10e', 'Bar à dîner', 'Festif'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/p/DW1gSFXiDcK/',
    description: 'Bar-restaurant festif rue de Paradis. Cuisine généreuse à partager, cocktails bien dosés et ambiance qui monte en puissance au fil de la soirée — le spot parfait avant une nuit dans le 10e.',
    lat: 48.8756, lng: 2.3512,
  },
  {
    id: '75',
    name: 'Casimir',
    cuisine: 'Française',
    city: 'Paris',
    address: '6 Rue de Belzunce, 75010',
    priceRange: '€€',
    rating: 4.6,
    cover: '#ECF8F6',
    coverEmoji: '🍺',
    tags: ['Bistrot', 'Château d\'Eau', 'Populaire'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/leparisdalexis',
    description: 'Un bistrot populaire et sans chichis près du Château d\'Eau. Plats généreux à prix doux, cave honnête et terrasse animée qui reflète bien l\'énergie de ce quartier en pleine effervescence.',
    lat: 48.8767, lng: 2.3542,
  },
  {
    id: '76',
    name: 'Oh My Jerk',
    cuisine: 'Antillaise',
    city: 'Paris',
    address: '3 Rue Eugène Varlin, 75010',
    priceRange: '€',
    rating: 4.6,
    cover: '#FFF8EC',
    coverEmoji: '🍖',
    tags: ['Jerk', 'Jamaïcain', 'Street food'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/leparisdalexis',
    description: 'Le meilleur jerk de Paris, rien que ça. Poulet et porc marinés aux épices jamaïcaines, cuits lentement sur charbon de bois — une explosion de saveurs pour quelques euros seulement.',
    lat: 48.8719, lng: 2.3630,
  },
  {
    id: '77',
    name: 'Qasti Bistrot',
    cuisine: 'Française',
    city: 'Paris',
    address: '205 Rue Saint-Martin, 75003',
    priceRange: '€€',
    rating: 4.5,
    cover: '#FDF8F4',
    coverEmoji: '🌍',
    tags: ['Fusion', 'Beaubourg', 'Créatif'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/leparisdalexis',
    description: 'Bistrot aux influences méditerranéennes et moyen-orientales près de Beaubourg. Cuisine créative qui voyage entre Paris et les épices du Levant, dans un cadre chaleureux et accessible.',
    lat: 48.8637, lng: 2.3543,
  },
  {
    id: '78',
    name: 'La Foccacceria',
    cuisine: 'Italienne',
    city: 'Paris',
    address: '104 Rue du Faubourg Poissonnière, 75010',
    priceRange: '€',
    rating: 4.6,
    cover: '#FDF0FD',
    coverEmoji: '🫓',
    tags: ['Focaccia', 'Italien', 'Faubourg'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/leparisdalexis',
    description: 'Focacce garnies à la ligurienne, préparées chaque matin dans des moules dorés. Garnitures généreuses, pain moelleux et croustillant — la pause déjeuner idéale du Faubourg Poissonnière.',
    lat: 48.8747, lng: 2.3493,
  },
  {
    id: '79',
    name: 'Jjin',
    cuisine: 'Coréenne',
    city: 'Paris',
    address: '35 Rue du Faubourg Saint-Denis, 75010',
    priceRange: '€€',
    rating: 4.6,
    cover: '#EBE9FA',
    coverEmoji: '♨️',
    tags: ['Coréen', 'Saint-Denis', 'Vapeur'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/p/DWooKbLiBJG/',
    description: 'Spécialiste du jjin — cuisson vapeur coréenne — dans l\'animation du Faubourg Saint-Denis. Mandu vapeur, poulet jjimdak et soupes réconfortantes servies dans un décor épuré.',
    lat: 48.8714, lng: 2.3552,
  },
  {
    id: '80',
    name: 'Drouant',
    cuisine: 'Française',
    city: 'Paris',
    address: '16-18 Place Gaillon, 75002',
    priceRange: '€€€€',
    rating: 4.8,
    cover: '#ECF8F6',
    coverEmoji: '🏛️',
    tags: ['Institution', 'Prix Goncourt', 'Gastronomique'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/p/DWmDjssCFw3/',
    description: 'L\'institution parisienne où le Prix Goncourt est décerné chaque année depuis 1914. Cuisine française de haute volée dans un décor Art déco somptueux, entre histoire et gastronomie.',
    lat: 48.8694, lng: 2.3392,
  },
  {
    id: '81',
    name: 'Chakaiseki Akiyoshi',
    cuisine: 'Japonaise',
    city: 'Paris',
    address: '59 Rue Letellier, 75015',
    priceRange: '€€€',
    rating: 4.8,
    cover: '#FDF0FD',
    coverEmoji: '🍵',
    tags: ['Kaiseki', 'Cérémonie du thé', 'Gastronomique'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/p/DWjgJa5iCc2/',
    description: 'L\'unique restaurant de chakaiseki en Europe — cuisine japonaise inspirée de la cérémonie du thé. Une expérience sensorielle d\'une rare poésie, portée par le chef Akiyoshi dans le calme du 15e.',
    lat: 48.8417, lng: 2.2985,
  },
  {
    id: '82',
    name: 'Rednoodle',
    cuisine: 'Chinoise',
    city: 'Paris',
    address: '23 Boulevard des Italiens, 75002',
    priceRange: '€€',
    rating: 4.5,
    cover: '#FFF8EC',
    coverEmoji: '🍜',
    tags: ['Nouilles', 'Grands Boulevards', 'Wok'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/p/DWg4iXpiM0r/',
    description: 'Nouilles chinoises tirées à la main sur les Grands Boulevards. Bouillons intenses, garnitures généreuses et cuisson au wok — une adresse qui casse les idées reçues sur la cuisine chinoise à Paris.',
    lat: 48.8710, lng: 2.3379,
  },
  {
    id: '83',
    name: 'BricktoPizza',
    cuisine: 'Italienne',
    city: 'Paris',
    address: '153 Quai de Valmy, 75010',
    priceRange: '€€',
    rating: 4.6,
    cover: '#FDF8F4',
    coverEmoji: '🍕',
    tags: ['Pizza', 'Canal Saint-Martin', 'Four à bois'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/p/DWUJz7YCI2o/',
    description: 'Pizzas cuites au four à brique face au Canal Saint-Martin. Pâte légèrement soufflée, garnitures généreuses et vue sur le canal — l\'adresse pizza incontournable du 10e.',
    lat: 48.8742, lng: 2.3650,
  },
  {
    id: '84',
    name: 'One and One',
    cuisine: 'Italienne',
    city: 'Paris',
    address: '7 Passage des Panoramas, 75002',
    priceRange: '€€',
    rating: 4.6,
    cover: '#ECF8F6',
    coverEmoji: '🫱🏼‍🫲🏼',
    tags: ['Passage couvert', 'Italian', 'Ambiance'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/p/DWRnJ9XCDiT/',
    description: 'Une table italienne nichée dans le mythique Passage des Panoramas. Antipasti, pastas fraîches et tiramisu maison dans un cadre historique chargé d\'une atmosphère unique.',
    lat: 48.8702, lng: 2.3454,
  },
  {
    id: '85',
    name: 'Il Était Un Square',
    cuisine: 'Française',
    city: 'Paris',
    address: '54 Rue Corvisart, 75013',
    priceRange: '€€',
    rating: 4.6,
    cover: '#F5FBF7',
    coverEmoji: '🌳',
    tags: ['Butte-aux-Cailles', 'Bistrot', 'Verdure'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/p/DWRnJ9XCDiT/',
    description: 'Un bistrot vert et chaleureux à deux pas de la Butte-aux-Cailles. Cuisine du marché honnête, belle sélection de vins nature et terrasse sur le square pour les beaux jours.',
    lat: 48.8323, lng: 2.3506,
  },
  {
    id: '86',
    name: 'Restaurant N+1',
    cuisine: 'Française',
    city: 'Paris',
    address: '151 Rue du Chevaleret, 75013',
    priceRange: '€€',
    rating: 4.6,
    cover: '#EBE9FA',
    coverEmoji: '🔬',
    tags: ['Chevaleret', 'Créatif', 'Confidentiel'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/leparisdalexis',
    description: 'Une table confidentielle dans le quartier des anciens entrepôts du 13e. Cuisine créative et précise, menu unique qui évolue selon les saisons et l\'humeur du chef.',
    lat: 48.8282, lng: 2.3665,
  },
  {
    id: '87',
    name: 'Les Frérots Paris',
    cuisine: 'Française',
    city: 'Paris',
    address: '117 Rue des Dames, 75017',
    priceRange: '€€',
    rating: 4.5,
    cover: '#FFF8EC',
    coverEmoji: '👬',
    tags: ['Batignolles', 'Bistrot', 'Convivial'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/p/DWRnJ9XCDiT/',
    description: 'Le bistrot convivial des Batignolles tenu par deux frères. Cuisine française généreuse et sans fioritures, plats du marché à l\'ardoise et ambiance de quartier irréprochable.',
    lat: 48.8847, lng: 2.3216,
  },
  {
    id: '88',
    name: 'Pâtisserie Melitot',
    cuisine: 'Française',
    city: 'Paris',
    address: '50 Rue de la Réunion, 75020',
    priceRange: '€',
    rating: 4.7,
    cover: '#FDF0FD',
    coverEmoji: '🌸',
    tags: ['Pâtisserie', '20e', 'Créatif'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/p/DWO_DxEhc4P/',
    description: 'La pâtisserie créative du 20e qui fait parler d\'elle bien au-delà du quartier. Entremets floraux, tartes aux saveurs audacieuses et viennoiseries qui disparaissent dès l\'ouverture.',
    lat: 48.8617, lng: 2.4024,
  },
  {
    id: '89',
    name: 'Biwan Irasshai',
    cuisine: 'Japonaise',
    city: 'Paris',
    address: '40 Rue du Louvre, 75001',
    priceRange: '€€€',
    rating: 4.7,
    cover: '#ECF8F6',
    coverEmoji: '🏮',
    tags: ['Japonais', 'Louvre', 'Izakaya'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/p/DWJzxEThtUh/',
    description: 'Izakaya japonais soigné face au Louvre. Yakitori de volaille fermière, gyoza maison et saké de qualité dans une atmosphère intimiste très éloignée des clichés de la cuisine nippone à Paris.',
    lat: 48.8623, lng: 2.3445,
  },
  {
    id: '90',
    name: 'Café de la Paix',
    cuisine: 'Française',
    city: 'Paris',
    address: '5 Place de l\'Opéra, 75009',
    priceRange: '€€€€',
    rating: 4.7,
    cover: '#EBE9FA',
    coverEmoji: '🎭',
    tags: ['Institution', 'Opéra', 'Classé'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/leparisdalexis',
    description: 'Monument historique classé, ouvert en 1862, face à l\'Opéra Garnier. Décor Second Empire somptueux, cuisine française grand-siècle et terrasse sur la Place de l\'Opéra pour observer le monde défiler.',
    lat: 48.8710, lng: 2.3310,
  },
  {
    id: '91',
    name: 'Osanchaise',
    cuisine: 'Française',
    city: 'Paris',
    address: '3 Rue Papillon, 75009',
    priceRange: '€€',
    rating: 4.5,
    cover: '#FDF8F4',
    coverEmoji: '🪑',
    tags: ['Faubourg Montmartre', 'Bistrot', 'Naturel'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/p/DWB15GHCJz6/',
    description: 'Un bistrot naturel confidentiel rue Papillon, dans l\'énergie du Faubourg Montmartre. Cuisine simple et bien faite, jolis vins de petits vignerons et ambiance décontractée de quartier.',
    lat: 48.8773, lng: 2.3460,
  },
  {
    id: '92',
    name: 'Fellows',
    cuisine: 'Française',
    city: 'Paris',
    address: '84 Rue du Faubourg Saint-Denis, 75010',
    priceRange: '€€',
    rating: 4.6,
    cover: '#F5FBF7',
    coverEmoji: '🤝',
    tags: ['Faubourg Saint-Denis', 'Bistronomique', 'Trendy'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/p/DV3CNKCCJxi/',
    description: 'L\'un des bistronomiques en vue du Faubourg Saint-Denis. Cuisine créative et accessible dans l\'un des couloirs les plus animés de Paris, avec une sélection de vins bien pensée.',
    lat: 48.8713, lng: 2.3555,
  },
  {
    id: '93',
    name: 'Le Quincy',
    cuisine: 'Française',
    city: 'Paris',
    address: '28 Avenue Ledru-Rollin, 75012',
    priceRange: '€€',
    rating: 4.5,
    cover: '#FDF5E6',
    coverEmoji: '🍷',
    tags: ['Bistrot', 'Rustique', 'Réservation obligatoire'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/p/DPvuYzAjPUK/',
    description: 'Spécialités régionales françaises et ambiance décontractée dans un décor rustique avec nappes en vichy rose.',
    lat: 48.8508, lng: 2.3697,
  },
  {
    id: '94',
    name: 'Le Bouclard',
    cuisine: 'Française',
    city: 'Paris',
    address: '1 Rue Cavallotti, 75018',
    priceRange: '€€',
    rating: 4.5,
    cover: '#F5F0EC',
    coverEmoji: '🍽',
    tags: ['Bistrot', 'Montmartre', 'Traditionnel'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/p/DXhJI3NCHBL/',
    description: 'Restaurant pittoresque servant des plats réconfortants maison d\'après des recettes de famille.',
    lat: 48.8848, lng: 2.3286,
  },
  {
    id: '95',
    name: 'La Grenouillère',
    cuisine: 'Française',
    city: 'La Madelaine-sous-Montreuil',
    address: 'La Madelaine-sous-Montreuil, 62170',
    priceRange: '€€€',
    rating: 4.8,
    cover: '#EDF5EE',
    coverEmoji: '🌿',
    tags: ['Gastronomique', 'Campagne', 'Nature'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/p/DWUQNUWiMic/?img_index=1',
    description: 'Table gastronomique d\'Alexandre Gauthier, nichée dans un hameau pittoresque de la Côte d\'Opale. Cuisine créative et sauvage au cœur d\'un domaine naturel exceptionnel.',
    lat: 50.4833, lng: 1.7167,
  },
  {
    id: '96',
    name: 'Elkano',
    cuisine: 'Espagnole',
    city: 'Getaria',
    address: 'Herrerieta Kalea, 2, 20808 Getaria, Gipuzkoa, Espagne',
    priceRange: '€€€',
    rating: 4.9,
    cover: '#EAF3FB',
    coverEmoji: '🐟',
    tags: ['Poisson', 'Pays Basque', 'Grill'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/p/DWRlZIqCDDl/',
    description: 'Adresse mythique de Getaria sur la côte basque espagnole. Grillades de poissons entiers au feu de bois, turbot et kokotxas de morue dans un cadre de village de pêcheurs.',
    lat: 43.2993, lng: -2.1996,
  },
  {
    id: '97',
    name: 'Asador Etxebarri',
    cuisine: 'Espagnole',
    city: 'Axpe',
    address: 'Plaza San Juan, 1, Axpe, Bizkaia, Espagne',
    priceRange: '€€€€',
    rating: 4.9,
    cover: '#FDF4EC',
    coverEmoji: '🔥',
    tags: ['Braise', 'Pays Basque', 'Gastronomique'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/p/DWMSV8uCJNo/',
    description: 'Victor Arguinzoniz a fait de la braise un art absolu dans ce village du Pays basque espagnol. Produits d\'exception cuits sur des grilles artisanales, régulièrement classé parmi les meilleurs restaurants du monde.',
    lat: 43.1167, lng: -2.6167,
  },
  {
    id: '98',
    name: 'La Petite Viennoise',
    cuisine: 'Française',
    city: 'Paris',
    address: '8 Rue de l\'École de Médecine, 75006',
    priceRange: '€€',
    rating: 4.5,
    cover: '#FFF8F0',
    coverEmoji: '🥐',
    tags: ['Bistrot', 'Saint-Germain', 'Cuisine autrichienne'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/p/DVoSa4uiE08/',
    description: 'Un bistrot viennois niché dans une rue discrète du 6e, entre Odéon et Saint-Michel. Schnitzel, goulasch et strudel dans un cadre chaleureux aux accents d\'Europe centrale.',
    lat: 48.8516, lng: 2.3438,
  },
  {
    id: '99',
    name: 'Patiné',
    cuisine: 'Française',
    city: 'Verneuil d\'Avre et d\'Iton',
    address: '98 Rue de la Ferté Vidame, 27130 Verneuil d\'Avre et d\'Iton',
    priceRange: '€€',
    rating: 4.7,
    cover: '#F5F0EC',
    coverEmoji: '🍽️',
    tags: ['Bistronomique', 'Normandie', 'Fait maison'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/p/DVY32ZrDAY-/',
    description: 'Une adresse bistronomique nichée dans la campagne normande, à Verneuil d\'Avre et d\'Iton. Cuisine du marché soignée, produits locaux et ambiance chaleureuse dans un cadre authentique.',
    lat: 48.7333, lng: 0.9167,
  },
  {
    id: '100',
    name: 'Les Fous de l\'île',
    cuisine: 'Française',
    city: 'Paris',
    address: '33 Rue des Deux Ponts, 75004',
    priceRange: '€€',
    rating: 4.5,
    cover: '#EDF5FB',
    coverEmoji: '🏝️',
    tags: ['Île Saint-Louis', 'Bistrot', 'Terrasse'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/p/DVG3bqiCDIq/',
    description: 'Un bistrot de caractère au cœur de l\'île Saint-Louis. Cuisine française généreuse et conviviale, terrasse aux beaux jours et atmosphère de village en plein Paris.',
    lat: 48.8518, lng: 2.3546,
  },
  {
    id: '101',
    name: 'Le Plomb du Cantal',
    cuisine: 'Française',
    city: 'Paris',
    address: '3 Rue de la Gaîté, 75014',
    priceRange: '€€',
    rating: 4.5,
    cover: '#F5F0EC',
    coverEmoji: '🧀',
    tags: ['Auvergnat', 'Fromage', 'Bistrot'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/p/DVG3bqiCDIq/',
    description: 'Une institution auvergnate rue de la Gaîté. Aligot filant, truffade et charcuteries du Cantal dans une ambiance chaleureuse et sans chichis, fidèle à la tradition depuis des décennies.',
    lat: 48.8395, lng: 2.3242,
  },
  {
    id: '102',
    name: 'La Petite Périgourdine',
    cuisine: 'Française',
    city: 'Paris',
    address: '2 Place du Panthéon, 75005',
    priceRange: '€€',
    rating: 4.5,
    cover: '#FDF4EC',
    coverEmoji: '🦆',
    tags: ['Périgord', 'Canard', 'Terroir'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/p/DVG3bqiCDIq/',
    description: 'Une table du Périgord en plein cœur du 5e, face au Panthéon. Foie gras, confit de canard et magret dans un cadre rustique et chaleureux, fidèle aux recettes du Sud-Ouest.',
    lat: 48.8462, lng: 2.3461,
  },
  {
    id: '103',
    name: 'L\'Auberge Aveyronnaise',
    cuisine: 'Française',
    city: 'Paris',
    address: '40 Rue Gabriel Lamé, 75012',
    priceRange: '€€',
    rating: 4.5,
    cover: '#F5F0EC',
    coverEmoji: '🥩',
    tags: ['Aveyron', 'Terroir', 'Bistrot'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/p/DVG3bqiCDIq/',
    description: 'Un morceau d\'Aveyron dans le 12e. Tripoux, aligot et estofinado dans une ambiance de guinguette conviviale, portés par la générosité de la cuisine paysanne du Rouergue.',
    lat: 48.8432, lng: 2.3812,
  },
  {
    id: '104',
    name: 'L\'Assaggio',
    cuisine: 'Italienne',
    city: 'Paris',
    address: '33-37 Rue Cambon, 75001',
    priceRange: '€€€',
    rating: 4.7,
    cover: '#FDF8F0',
    coverEmoji: '🍝',
    tags: ['Italien', 'Luxe', 'Tuileries'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/p/DU8uo40CL2v/',
    description: 'Le restaurant italien de l\'hôtel Castille, à deux pas de la Place Vendôme. Pâtes fraîches, risottos et produits transalpins d\'exception dans un cadre élégant et feutré.',
    lat: 48.8659, lng: 2.3289,
  },
  {
    id: '105',
    name: 'Anne',
    cuisine: 'Française',
    city: 'Paris',
    address: '28 Place des Vosges, 75003',
    priceRange: '€€€',
    rating: 4.7,
    cover: '#F5EEF8',
    coverEmoji: '🏛️',
    tags: ['Place des Vosges', 'Gastronomique', 'Élégant'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/p/DU8uo40CL2v/',
    description: 'Sous les arcades de la Place des Vosges, Anne propose une cuisine gastronomique française dans l\'un des plus beaux cadres de Paris. Produits nobles, assiettes précises et service attentionné.',
    lat: 48.8554, lng: 2.3625,
  },
  {
    id: '106',
    name: 'Rôtisserie Ségar',
    cuisine: 'Française',
    city: 'Paris',
    address: '11 Rue des Deux Ponts, 75004',
    priceRange: '€€',
    rating: 4.6,
    cover: '#FDF4EC',
    coverEmoji: '🍗',
    tags: ['Rôtisserie', 'Île Saint-Louis', 'Fait maison'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/p/DU0452NDGPt/',
    description: 'La rôtisserie de l\'île Saint-Louis. Poulets rôtis à la broche, pommes de terre fondantes et jus dorés dans un cadre simple et gourmand, fidèle à la grande tradition française.',
    lat: 48.8518, lng: 2.3546,
  },
  {
    id: '107',
    name: 'Le Canard Sauvage',
    cuisine: 'Française',
    city: 'Paris',
    address: '14 Boulevard de Strasbourg, 75010',
    priceRange: '€€',
    rating: 4.6,
    cover: '#EDF5FB',
    coverEmoji: '🦆',
    tags: ['Bistrot', 'Canal Saint-Martin', 'Canard'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/p/DUTeh3KDJrL/',
    description: 'Un bistrot canaille boulevard de Strasbourg, dans l\'effervescence du 10e. Cuisine française généreuse autour du canard, vins nature et ambiance chaleureuse de quartier.',
    lat: 48.8706, lng: 2.3554,
  },
  {
    id: '108',
    name: 'Le Petit Vendôme',
    cuisine: 'Française',
    city: 'Paris',
    address: '14 Boulevard de Strasbourg, 75010',
    priceRange: '€€',
    rating: 4.5,
    cover: '#FFF8EC',
    coverEmoji: '🥪',
    tags: ['Bistrot', 'Sandwich', 'Traditionnel'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/p/DUGhuakiOop/',
    description: 'Un classique parisien fidèle à lui-même. Sandwichs généreux, plats du jour à l\'ardoise et zinc animé dans une ambiance bistrotière authentique.',
    lat: 48.8706, lng: 2.3554,
  },
  {
    id: '109',
    name: 'La Boule Rouge',
    cuisine: 'Française',
    city: 'Paris',
    address: '1 Rue de la Boule Rouge, 75009',
    priceRange: '€€',
    rating: 4.5,
    cover: '#FDF0F0',
    coverEmoji: '🔴',
    tags: ['Bistrot', 'Grands Boulevards', 'Traditionnel'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/p/DT8Q734CBm7/',
    description: 'Un bistrot parisien authentique niché rue de la Boule Rouge, dans le 9e. Cuisine française de tradition, plats du jour généreux et ambiance de comptoir chaleureuse.',
    lat: 48.8724, lng: 2.3454,
  },
  {
    id: '110',
    name: 'Patsy',
    cuisine: 'Américaine',
    city: 'Paris',
    address: '26 Rue Bergère, 75009',
    priceRange: '€€',
    rating: 4.5,
    cover: '#FFF8EC',
    coverEmoji: '🍕',
    tags: ['Pizza', 'Grands Boulevards', 'New-yorkais'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/p/DTqQNYhiCJT/',
    description: 'Une pizzeria new-yorkaise dans le 9e, inspirée de la légendaire Patsy\'s de Harlem. Pizzas fines à la pâte croustillante, cuites au feu de bois dans une ambiance décontractée.',
    lat: 48.8734, lng: 2.3469,
  },
  {
    id: '111',
    name: 'Le Mâche-dru',
    cuisine: 'Française',
    city: 'Paris',
    address: '60 Rue Saint-Louis en l\'île, 75004',
    priceRange: '€€',
    rating: 4.6,
    cover: '#F5F0EC',
    coverEmoji: '🥗',
    tags: ['Île Saint-Louis', 'Bistrot', 'Marché'],
    recommendedBy: { handle: '@philoudarblay', name: 'Philou d\'Arblay', followers: '153K', avatar: '👩‍🍳' },
    instagramPost: 'https://www.instagram.com/p/DTLTL3dCAOy/',
    description: 'Un bistrot de marché sur la rue principale de l\'île Saint-Louis. Cuisine du quotidien soignée, produits frais et ambiance de quartier dans l\'un des coins les plus charmants de Paris.',
    lat: 48.8513, lng: 2.3573,
  },
  {
    id: '112',
    name: 'Bonne Table',
    cuisine: 'Française',
    city: 'Paris',
    address: '7 Rue du Commandant Rivière, 75008',
    priceRange: '€€',
    rating: 4.6,
    cover: '#F5FBF7',
    coverEmoji: '🌿',
    tags: ['Bistronomique', 'Champs-Élysées', 'Déjeuner'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/p/DXlpclnCOVR/',
    description: 'Une table bistronomique soignée dans le 8e, à deux pas des Champs-Élysées. Cuisine du marché, produits frais et carte courte qui change au fil des saisons.',
    lat: 48.8719, lng: 2.3098,
  },
  {
    id: '113',
    name: 'Bonne Table',
    cuisine: 'Française',
    city: 'Paris',
    address: '43 Rue Godot de Mauroy, 75009',
    priceRange: '€€',
    rating: 4.6,
    cover: '#F5FBF7',
    coverEmoji: '🌿',
    tags: ['Bistronomique', 'Opéra', 'Déjeuner'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/p/DXlpclnCOVR/',
    description: 'La seconde adresse Bonne Table, dans le 9e près de l\'Opéra. Même esprit bistronomique, cuisine du marché généreuse et cadre convivial.',
    lat: 48.8722, lng: 2.3356,
  },
  {
    id: '114',
    name: 'Kare',
    cuisine: 'Japonaise',
    city: 'Paris',
    address: '76 Rue Mazarine, 75006',
    priceRange: '€€',
    rating: 4.6,
    cover: '#FDF8F0',
    coverEmoji: '🍛',
    tags: ['Curry japonais', 'Saint-Germain', 'Fait maison'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/p/DXetQjZiD4n/',
    description: 'Le spécialiste du curry japonais dans le 6e. Kare propose des currys mijotés maison, riches et parfumés, dans un cadre épuré et chaleureux très apprécié du quartier.',
    lat: 48.8530, lng: 2.3381,
  },
  {
    id: '115',
    name: 'Kare',
    cuisine: 'Japonaise',
    city: 'Paris',
    address: '10 Rue Dauphine, 75006',
    priceRange: '€€',
    rating: 4.6,
    cover: '#FDF8F0',
    coverEmoji: '🍛',
    tags: ['Curry japonais', 'Odéon', 'Fait maison'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/p/DXetQjZiD4n/',
    description: 'La seconde adresse Kare, rue Dauphine dans le 6e. Currys japonais maison, mijotés longuement, à déguster dans un cadre minimaliste et accueillant.',
    lat: 48.8539, lng: 2.3393,
  },
  {
    id: '116',
    name: 'Vidam',
    cuisine: 'Française',
    city: 'Paris',
    address: '34 Rue de Cambrai, 75019',
    priceRange: '€€',
    rating: 4.6,
    cover: '#EDF5FB',
    coverEmoji: '🍽️',
    tags: ['Bistronomique', 'Villette', 'Créatif'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/p/DXR08icCI9K/?img_index=1',
    description: 'Une table bistronomique créative dans le 19e, près de la Villette. Cuisine du marché inventive, carte courte et vins nature dans un cadre chaleureux et décontracté.',
    lat: 48.8877, lng: 2.3763,
  },
  {
    id: '117',
    name: 'Rôtisserie CotCotGardette',
    cuisine: 'Française',
    city: 'Paris',
    address: '22 Rue Rochebrune, 75011',
    priceRange: '€€',
    rating: 4.6,
    cover: '#FDF4EC',
    coverEmoji: '🍗',
    tags: ['Rôtisserie', 'Oberkampf', 'Fait maison'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/p/DXMrjcJCH1H/',
    description: 'La rôtisserie du 11e, à deux pas de la place Gardette. Poulets rôtis à la broche, accompagnements maison et jus dorés dans une ambiance de quartier chaleureuse.',
    lat: 48.8617, lng: 2.3785,
  },
  {
    id: '119',
    name: 'Kasumi',
    cuisine: 'Japonaise',
    city: 'Paris',
    address: '38 Rue Balard, 75015',
    priceRange: '€€',
    rating: 4.6,
    cover: '#ECF8F6',
    coverEmoji: '🍣',
    tags: ['Japonais', 'Balard', 'Sushi'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/p/DXHhwazCFX-/',
    description: 'Une table japonaise soignée dans le 15e. Sushis et cuisine nippone préparés avec des produits frais, dans un cadre épuré et calme loin de l\'agitation du centre.',
    lat: 48.8449, lng: 2.2906,
  },
  {
    id: '118',
    name: 'Pâtisserie Adroyte',
    cuisine: 'Française',
    city: 'Paris',
    address: '14 Rue Froissart, 75003',
    priceRange: '€',
    rating: 4.7,
    cover: '#FFF8F0',
    coverEmoji: '🧁',
    tags: ['Pâtisserie', 'Marais', 'Créatif'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/p/DXKHiFNiMyc/',
    description: 'Une pâtisserie créative nichée dans le Haut-Marais. Entremets soignés, tartes aux saveurs originales et viennoiseries travaillées dans un cadre élégant et minimaliste.',
    lat: 48.8622, lng: 2.3617,
  },
  {
    id: '120',
    name: 'Navigli Aperitivo',
    cuisine: 'Italienne',
    city: 'Paris',
    address: '52 Rue d\'Enghien, 75010',
    priceRange: '€€',
    rating: 4.5,
    cover: '#FDF8F0',
    coverEmoji: '🍷',
    tags: ['Italien', 'Aperitivo', 'Canal Saint-Martin'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/p/DXHhwazCFX-/',
    description: 'L\'esprit de l\'aperitivo milanais transposé dans le 10e. Spritz, planches de charcuteries italiennes et ambiance conviviale du soir dans un cadre chaleureux.',
    lat: 48.8726, lng: 2.3523,
  },
  {
    id: '121',
    name: 'Star Grill Barbecue',
    cuisine: 'Américaine',
    city: 'Ivry-sur-Seine',
    address: '12 Avenue Verdun, 94200 Ivry-sur-Seine',
    priceRange: '€€',
    rating: 4.5,
    cover: '#FFF4EC',
    coverEmoji: '🔥',
    tags: ['Barbecue', 'Ivry', 'Grillades'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/p/DXHhwazCFX-/',
    description: 'Un barbecue américain généreux à Ivry-sur-Seine. Viandes fumées lentement, ribs et burgers copieux dans une ambiance décontractée juste aux portes de Paris.',
    lat: 48.8133, lng: 2.3839,
  },
  {
    id: '122',
    name: 'Kushikatsu Bon Paris',
    cuisine: 'Japonaise',
    city: 'Paris',
    address: '24 Rue Jean-Pierre Timbaud, 75011',
    priceRange: '€€',
    rating: 4.6,
    cover: '#FDF8F0',
    coverEmoji: '🍢',
    tags: ['Kushikatsu', 'Oberkampf', 'Japonais'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/p/DW_BnwViM-R/',
    description: 'Le spécialiste des kushikatsu dans le 11e. Brochettes panées et frites selon la tradition d\'Osaka, à tremper dans la sauce maison, dans une ambiance izakaya chaleureuse.',
    lat: 48.8647, lng: 2.3739,
  },
  {
    id: '123',
    name: 'Black Angus',
    cuisine: 'Américaine',
    city: 'Paris',
    address: '8 Place de la République, 75011',
    priceRange: '€€',
    rating: 4.5,
    cover: '#F5F0EC',
    coverEmoji: '🥩',
    tags: ['Steak', 'République', 'Viande'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/p/DW9PPhfCDtu/',
    description: 'La référence du steak Black Angus à Paris. Viandes sélectionnées, cuissons maîtrisées et frites maison dans un cadre convivial et animé.',
    lat: 48.8674, lng: 2.3634,
  },
  {
    id: '124',
    name: 'Black Angus',
    cuisine: 'Américaine',
    city: 'Paris',
    address: '96 Rue Saint-Lazare, 75009',
    priceRange: '€€',
    rating: 4.5,
    cover: '#F5F0EC',
    coverEmoji: '🥩',
    tags: ['Steak', 'Saint-Lazare', 'Viande'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/p/DW9PPhfCDtu/',
    description: 'La seconde adresse Black Angus, côté Saint-Lazare. Même sélection de viandes Black Angus, mêmes cuissons précises dans un cadre moderne et accueillant.',
    lat: 48.8762, lng: 2.3279,
  },
  {
    id: '125',
    name: 'Khun Akorn',
    cuisine: 'Thaïlandaise',
    city: 'Paris',
    address: '8 Avenue de Taillebourg, 75011',
    priceRange: '€€',
    rating: 4.7,
    cover: '#F5FBF7',
    coverEmoji: '🌿',
    tags: ['Thaïlandais', 'Nation', 'Authentique'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/p/DW4E8F3iGCV/',
    description: 'Une institution thaïlandaise du 11e, tenue par la famille Akorn depuis des années. Cuisine thaïe authentique et parfumée, loin des versions édulcorées — curry, pad thaï et soupes mijotées.',
    lat: 48.8489, lng: 2.3957,
  },
  {
    id: '126',
    name: 'Qasti Bistrot',
    cuisine: 'Française',
    city: 'Paris',
    address: '205 Rue Saint-Martin, 75003',
    priceRange: '€€',
    rating: 4.6,
    cover: '#F5F0EC',
    coverEmoji: '🍽️',
    tags: ['Bistrot', 'Arts et Métiers', 'Bistronomique'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/p/DWtyOyXCMos/',
    description: 'Un bistrot bistronomique discret rue Saint-Martin, dans le 3e. Cuisine du marché soignée, carte courte et vins choisis dans un cadre chaleureux et sans chichis.',
    lat: 48.8630, lng: 2.3524,
  },
  {
    id: '127',
    name: 'Qasti Shawarma & Grill',
    cuisine: 'Libanaise',
    city: 'Paris',
    address: '214 Rue Saint-Martin, 75003',
    priceRange: '€',
    rating: 4.5,
    cover: '#FDF8F0',
    coverEmoji: '🌯',
    tags: ['Shawarma', 'Arts et Métiers', 'Street food'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/p/DWtyOyXCMos/',
    description: 'Le comptoir street food de Qasti, en face du bistrot. Shawarmas généreux, grillades et mezzes à emporter ou sur place dans une ambiance décontractée.',
    lat: 48.8631, lng: 2.3523,
  },
  {
    id: '128',
    name: 'Faurn',
    cuisine: 'Française',
    city: 'Paris',
    address: '212 Rue Saint-Martin, 75003',
    priceRange: '€€',
    rating: 4.5,
    cover: '#FDF4EC',
    coverEmoji: '🔥',
    tags: ['Bistrot', 'Arts et Métiers', 'Braise'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/p/DWtyOyXCMos/',
    description: 'Une adresse de caractère rue Saint-Martin, dans le 3e. Cuisine au feu de bois, produits sourcés avec soin et atmosphère chaleureuse à deux pas du Conservatoire des Arts et Métiers.',
    lat: 48.8631, lng: 2.3523,
  },
  {
    id: '129',
    name: 'Qasti Pâtisserie',
    cuisine: 'Française',
    city: 'Paris',
    address: '212 Rue Saint-Martin, 75003',
    priceRange: '€',
    rating: 4.6,
    cover: '#FFF8F0',
    coverEmoji: '🧁',
    tags: ['Pâtisserie', 'Arts et Métiers', 'Orientale'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/p/DWtyOyXCMos/',
    description: 'La pâtisserie de la famille Qasti, rue Saint-Martin. Douceurs orientales revisitées, baklawa modernes et créations sucrées qui mêlent tradition du Levant et pâtisserie française.',
    lat: 48.8631, lng: 2.3523,
  },
  {
    id: '130',
    name: 'La Focacceria',
    cuisine: 'Italienne',
    city: 'Paris',
    address: '7 Rue de la Verrerie, 75004',
    priceRange: '€',
    rating: 4.6,
    cover: '#FDF8F0',
    coverEmoji: '🫓',
    tags: ['Focaccia', 'Marais', 'Italien'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/p/DWtAJNqiHVt/',
    description: 'Spécialiste de la focaccia dans le Marais. Pain moelleux garni de produits italiens de qualité, à emporter ou sur place dans un cadre simple et convivial.',
    lat: 48.8553, lng: 2.3514,
  },
  {
    id: '131',
    name: 'Il était un burger...',
    cuisine: 'Américaine',
    city: 'Paris',
    address: '78 Rue Mouffetard, 75005',
    priceRange: '€€',
    rating: 4.5,
    cover: '#FFF8EC',
    coverEmoji: '🍔',
    tags: ['Burger', 'Mouffetard', 'Fait maison'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/p/DWbFQ7QCP6_/',
    description: 'Un burger artisanal rue Mouffetard, dans l\'animation du 5e. Pains briochés maison, viandes sélectionnées et sauces signature pour un burger généreux loin des chaînes.',
    lat: 48.8442, lng: 2.3503,
  },
  {
    id: '132',
    name: 'Le Beef Marais',
    cuisine: 'Américaine',
    city: 'Paris',
    address: '33 Rue des Rosiers, 75004',
    priceRange: '€€',
    rating: 4.5,
    cover: '#F5F0EC',
    coverEmoji: '🥩',
    tags: ['Steak', 'Marais', 'Burger'],
    recommendedBy: { handle: '@leparisdalexis', name: 'Le Paris d\'Alexis', followers: '825K', avatar: '🗼' },
    instagramPost: 'https://www.instagram.com/p/DVtie4XiIzt/',
    description: 'Une adresse carnivore au cœur du Marais, rue des Rosiers. Steaks et burgers généreux, viandes sélectionnées et frites maison dans une ambiance décontractée.',
    lat: 48.8551, lng: 2.3569,
  },
]
